### ISSUE TITLE
Unable to run the example app

### ISSUE THREAD

**Issue by railsstudent** [ferrerojosh/nest-keycloak-connect#103]
When I ran the example app, it could not start and reflector could not inject.

[Nest] 32058  - 24/12/2021, 11:36:55 am   ERROR [ExceptionHandler] Nest can't resolve dependencies of the AuthGuard (KEYCLOAK_INSTANCE, KEYCLOAK_CONNECT_OPTIONS, KEYCLOAK_LOGGER, ?). Please make sure that the argument Reflector at index [3] is available in the AppModule context.

Potential solutions:
- If Reflector is a provider, is it part of the current AppModule?
- If Reflector is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing Reflector */ ]
  })

Error: Nest can't resolve dependencies of the AuthGuard (KEYCLOAK_INSTANCE, KEYCLOAK_CONNECT_OPTIONS, KEYCLOAK_LOGGER, ?). Please make sure that the argument Reflector at index [3] is available in the AppModule context.

Please kindly advise.

**Comment by deeeed** [comment]
+1

**Comment by ferrerojosh** [comment]
This is a problem with Nest 8. A temporary solution would be to install `nest-keycloak-connect` on the example app and remove the local typescript link in tsconfig.json I'll make a change that does this.

**Comment by railsstudent** [comment]
Thank you for the prompt response.
