### ISSUE TITLE
Question: Use Case with Keycloak

### ISSUE THREAD

**Issue by smolinari** [ferrerojosh/nest-keycloak-connect#105]
Hi,

Sorry, but I didn't know where else to ask this and hope you/ someone can offer some guidance. 

I have a fair understanding of what Keycloak can offer and I'd like to explain my use case and basically ask if Keycloak is overkill or a good choice for user authentication/ authorization management. 

What I'm looking for first and foremost is a user authentication system (OAuth), where tenants would have a centrally located user base. These users could have access to any number of application APIs/ apps. 

There would be three types of users with different levels of access. 

1. Devs and Administrators
2. Team members
3. Customers/ Clients/Registered Users

Level 1 and 2 is part of an organization (company, non-profit, startup, etc). An organization is a tenant. There could be any number of apps to support these different levels of user, however, only certain users should be given access to those apps.  

Level 3 users can only access "public facing" apps. Level 1 and level 2 apps are "off limits" completely and tenants shouldn't be able to circumvent this in any way programmatically. 

The apps themselves will have an internal Attribute Based Access Control system and won't need centrally controlled access management. So, basically user data needs to be co-located, meaning the users will have local and centralized versions of their user data.  

Level 1 users should be able to "imitate" level 2 and 3 users as they would have permissions set up via the local ABAC system, in order to check locally the set ABAC rules. 

Those are my current requirements. I feel Keycloak is a good fit, just that it offers the fine grained ABAC management centrally, and I'd like to not have it centralized. Does that make sense?

Hoping for some guidance. Thanks in advance. 

Scott

**Comment by ferrerojosh** [comment]
Keycloak should be able to do what you want. I'm no Keycloak expert myself but I think their policy enforcer if setup correctly, is able to correctly do ABAC. You can even develop your own server plugins if really needed.

This library merely calls Keycloak's policy enforcer and asks the Keycloak instance if the request can go through. You can customize the policies in many ways you want as stated here: https://www.keycloak.org/docs/latest/authorization_services/

**Comment by smolinari** [comment]
Thanks. I figured it might be a bit of an overkill. I don't want full user management, as each tenant instance will have its own ABAC system. I only need to have special roles, so like license types. Those license types (1 and 2 mentioned above) would have access to specialized apps. And, I'm looking for a centralized user management for the user's sake. I'm also looking at FusionAuth to fill this need. It also looks promising.

Thanks again.

Scott
