### ISSUE TITLE
retrieve user context from service layer

### ISSUE THREAD

**Issue by deeeed** [ferrerojosh/nest-keycloak-connect#107]
How can I directly retrieve user information in my service layer?
``` 
// Something like that:
const user = getSecurityContext().authenticatedUser()
```

If I am on the Controller Layer I would use:
```
@Post()
  create(@AuthenticatedUser() user: any, @Body() createArticleDto: CreateArticleDto) {
    this.logger.debug(`create user now`, user);
    return this.articlesService.create(user, createArticleDto);
  }
```
But then I need to pass it down to all my services...

Is there a better way to do it?

**Comment by sgentile** [comment]
I was wondering the same - ie. can the keycloak token be accessible in the context object

**Comment by ferrerojosh** [comment]
Its due to how node is built that we can't do any thread-local stuff like this. I know that `cls-hooked` exists, but if I were to do this, I want it in a way that won't let me hack into nest itself.

**Comment by ferrerojosh** [comment]
Also a `REQUEST` injection token exists in nest, if that can help you in any way: https://docs.nestjs.com/fundamentals/injection-scopes#request-provider

**Comment by sgentile** [comment]
I did see the @AuthenticatedUser() attribute, this is exactly what I needed

**Comment by ferrerojosh** [comment]
> Could we use:
> 
> ```
> @AuthenticatedUser(context) const user; // something to extract a user object from the Request context the service layer?
> ```
> 
> I am just picking up on Nest, coming from Java so still trying to figure things out...

You can't. Java is built different as it has thread-local support and is multi-threaded compared to Node.

As for this issue, as I mentioned earlier can be done like this:
```typescript
import { Injectable, Scope, Inject } from '@nestjs/common';
import { REQUEST } from '@nestjs/core';
import { Request } from 'express';

@Injectable({ scope: Scope.REQUEST })
export class CatsService {
  user: any;
  constructor(@Inject(REQUEST) private request: Request) {
    // @AuthenticatedUser just basically grabs request.user and injects it
    this.user = request.user;
  }
}
```

**Comment by deeeed** [comment]
Thanks for the code sample.
I tried but typescript seems unhappy:
Property 'user' does not exist on type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>'.

**Comment by deeeed** [comment]
Thanks for the code sample.
Unfortunately, user property doesn't seem to be available on the request.
Do I need to import/inject something in the module file as well to decorate the request with user info?

**Comment by deeeed** [comment]
If the user isn't available, does it mean it needs to be extracted from the token first?

**Comment by deeeed** [comment]
A couple of things I noticed when playing around.

**auth.guard.ts**:
- incompatible types on extractJWTFromCookie ( headers is [key:string]: string but nest uses [key:string]: string | string[]  which creates warning. Maybe the ts rules are not strict enough on the project?
- I can have user in my service layer if I duplicate the token extraction code but why the request isn't populated from the controller layer?

Eventually here is my code (without token validation which have been done in controller):
```ts
private user: any;
  private readonly logger = new Logger(ArticlesService.name);

  constructor(
    @Inject(REQUEST) private req: Request,
    @InjectModel(Article.name) private readonly model: Model<ArticleDocument>,
  ) {
    // I already check in @Controller that user is allowed, why isn't the request decorated?
    if (!req['user']) {
      const jwt = this.extractJwtFromCookie(req.cookies) ?? this.extractJwt(req.headers as { [key: string]: string });
      this.logger.verbose(`User JWT: ${jwt}`);

      // Attach user info object
      req['user'] = parseToken(jwt as string);
      // Attach raw access token JWT extracted from bearer/cookie
      req['accessTokenJWT'] = jwt;
    }
    this.user = req['user'];
  }

  private extractJwt(headers: { [key: string]: string }) {
    if (headers && !headers.authorization) {
      this.logger.verbose(`No authorization header`);
      return null;
    }

    const auth = headers.authorization.split(' ');

    // We only allow bearer
    if (auth[0].toLowerCase() !== 'bearer') {
      this.logger.verbose(`No bearer header`);
      return null;
    }

    return auth[1];
  }

  private extractJwtFromCookie(cookies: { [key: string]: string | string[] }) {
    const cookieKey = KEYCLOAK_COOKIE_DEFAULT;

    return cookies && cookies[cookieKey];
  }
```
This seems to be a common design issue to avoid populating down a user instance between layers. Should I open a separate issue for discussion?

**Comment by ferrerojosh** [comment]
User property won't be available if you don't have `AuthGuard` in your module or controller.

**Comment by ferrerojosh** [comment]
As for populating down the user instance between layers, I get what you mean, like I said, nodejs just doesn't have native thread-local like state that is used in common frameworks like spring to store session/auth context. This is a nodejs problem, can be done  using `cls-hooked` but I'll avoid doing that when necessary.

Until Nest itself makes it easier to create a session context, the only way for now would be injecting the `REQUEST` token in a `SESSION` scope and grabbing `request.user`.

**Comment by sgentile** [comment]
All that was required:

```
import { AuthenticatedUser } from 'nest-keycloak-connect';

@Query('user')
    async user(@AuthenticatedUser() user) {
        // this is injected similar to context and is not included as a field you pass in
        // ...  user here has all the fields from the keycloak token ... sub (id), email, etc...

    }
    ```

**Comment by sgentile** [comment]
> As for populating down the user instance between layers, I get what you mean, like I said, nodejs just doesn't have native thread-local like state that is used in common frameworks like spring to store session/auth context. This is a nodejs problem, can be done using `cls-hooked` but I'll avoid doing that when necessary.
> 
> Until Nest itself makes it easier to create a session context, the only way for now would be injecting the `REQUEST` token in a `SESSION` scope and grabbing `request.user`.

correct, we just pass it :

```
@Mutation(() => Boolean)
    @Authorized()
    async shareTechnology(
        @PubSub('NOTIFICATIONS') publish: Publisher<NotificationMessagePayload>,
        @Ctx('user') user: User,
        ...
    ) {
        return await this.technologyService.share(user, publish, ...);
    }
```

**Comment by deeeed** [comment]
Thanks for the additional code and sorry if I wasn't clear. 

I do have access to the user instance inside the Controller layer because AuthGuard is in my module. I was just trying to avoid passing down the user from Controller Layer to Service Layer.
Having access to the request makes it possible to parse the token in the Service Layer (as per provided code) but it is inefficient since it was already parsed in the controller layer and I thought there would be another way to re-use it.

I will read more on cls-hooked.

**Comment by ferrerojosh** [comment]
> cls-hooked

Here's an interesting gist if you like: https://gist.github.com/bengry/924a9b93c25d8a98bffdfc0a847f0dbe
