### ISSUE TITLE
Multi tenancy with bearer-only

### ISSUE THREAD

**Issue by KlausNie** [ferrerojosh/nest-keycloak-connect#109]
I'd like to set up multi tenancy with bearer-only clients.

The idea is:
* in the web frontend, the user retrieves his token via login (public client)
* in the backend, that user is verified via the bearer-only client
* the realm can on the backend be extracted from the request (that is already possible, as seen in the documentation, last part)

The documentation only explains how to do it with a confidential client: extract the already present secret of the client and make the request via that).

What I'd like to do is to use the token provided by the user (which he retrieved beforehand via login) and use that to authenticate/authorize the API endpoint.

Is such a thing possible?

For reference: #93 & #102

**Comment by ferrerojosh** [comment]
Did you try enabling `bearerOnly` mode while having multi-tenancy setup ?

**Comment by KlausNie** [comment]
Yes! The problem is: how do I pass along the `bearer` token?

When I use the `bearer-only` client setup, I will have no `client-secret` that I could use, but instead I'd have to use the bearer token from the original request and give it to the lib so that it can make the authentication/authorization request instead.

I cannot use the `realmSecretResolver`, since that would require the input of it to be a `request`. 
And even then, the `realmSecretResolver` would set the wrong header since it sets the header for the secret, and there is no way to set the `bearer` token, right?

I'd need a way to pass along the token or to tell the library to take it from the request by itself.

**Comment by ferrerojosh** [comment]
I am honestly confused. The library already grabs the bearer token in the request headers by default and uses those tokens to pass them through the policy enforcer (if needed be). Setting the `client-id` and `secret` only allows you to authenticate/authorize users via Keycloak. You can always have `realmSecretResolver` return null to tell the keycloak library that you don't have one.

My understanding of `bearer-only` is not that great all I know is that it is practically used in service to service communications.

**Comment by KlausNie** [comment]
So it automatically grabs the token from the request by default? Hmm, that is what I actually require... so it should work already.

For some reason it does not work for me. I always get
```
11:59:07,230 TRACE [org.keycloak.events] (default task-348) type=INTROSPECT_TOKEN_ERROR, realmId=master, clientId=api, userId=null, ipAddress=82.144.35.106, error=invalid_request, detail='Authentication failed.', requestUri=http://develop.auth.tediro.quickbirdmedical.com:8080/auth/realms/master/protocol/openid-connect/token/introspect, stackTrace=
    org.keycloak.keycloak-services@16.1.0//org.keycloak.events.log.JBossLoggingEventListenerProvider.logEvent(JBossLoggingEventListenerProvider.java:114)
    org.keycloak.keycloak-server-spi-private@16.1.0//org.keycloak.events.EventListenerTransaction.commitImpl(EventListenerTransaction.java:62)
    org.keycloak.keycloak-server-spi@16.1.0//org.keycloak.models.AbstractKeycloakTransaction.commit(AbstractKeycloakTransaction.java:48)
    org.keycloak.keycloak-services@16.1.0//org.keycloak.services.DefaultKeycloakTransactionManager.commit(DefaultKeycloakTransactionManager.java:146)
    org.keycloak.keycloak-services@16.1.0//org.keycloak.services.filters.AbstractRequestFilter.close(AbstractRequestFilter.java:64)
    org.keycloak.keycloak-services@16.1.0//org.keycloak.services.filters.AbstractRequestFilter.filter(AbstractRequestFilter.java:49)
    org.keycloak.keycloak-wildfly-extensions@16.1.0//org.keycloak.provider.wildfly.WildFlyRequestFilter.doFilter(WildFlyRequestFilter.java:39)
    io.undertow.servlet@2.2.14.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
    io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
    io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
    io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
    io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
    io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
    org.wildfly.security.elytron-web.undertow-server@1.10.1.Final//org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler.lambda$handleRequest$1(ElytronRunAsHandler.java:68)
```
in keycloak and 
```
[0] [Nest] 86191  - 02/07/2022, 12:59:07 PM VERBOSE [Keycloak] Using token validation method: ONLINE
[0] [Nest] 86191  - 02/07/2022, 12:59:07 PM    WARN [Keycloak] Cannot validate access token: Error: 401:Unauthorized
```
in the NestJS application.

I've got a frontend application where the login is done. For that, I have a client set up (`web`) which retrieves the initial token.
Then I've got the NestJS server where I want to set up a verification that the user is allowed to request this endpoint by verifying it via keycloak.
```javascript
    KeycloakConnectModule.register({
        authServerUrl: process.env.KEYCLOAK_URL,
        clientId: 'api', //process.env.KEYCLOAK_CLIENT_ID,
        multiTenant: {
            realmResolver: () => 'master',
            realmSecretResolver: (realm) => null,
        },
        secret: 'fallback-secret-should-never-be-needed',
        "bearer-only": true,
        bearerOnly: true, // I've set both, since I wasn't sure which one needs setting

        logLevels: ['error', 'warn'],
        useNestLogger: true,
        policyEnforcement: PolicyEnforcementMode.ENFORCING,
        tokenValidation: TokenValidation.ONLINE,
    });
```
For that, I've got another client set up `api` which is set to `bearer-only` in keycloak.

Any idea what I could be doing wrong?



While writing this, I figured out, how I can get it to work:
The `nestjs-keycloak-connect` still does need a `client-secret` to work as a `bearer-only` client.
I probably know even less than you about keycloak intended this to work, but to me, it seems unintuitive that for a `bearer-only` client the `client-secret` is still required. Shouldn't that one work with the bearer token alone?

The problem I have with the `client-secret` is that it gives more access than a simple bearer token. A bearer token only gives that specific user access to whatever he has access to. The `client-secret` authenticates the client and so if someone gets a hold of that one, that person has access to possibly all users that client+realm combination contains.... does that make sense?

**Comment by ferrerojosh** [comment]
Yeah I get what you mean, I am still trying to find out how to do this without breaking things. It isn't documented that well in Keycloak's documentation either, it just says just to pass `bearer-only` and it will do the magic.

**Comment by KlausNie** [comment]
I'm not 100% sure it is even possible. It could be that keycloak just requires the `client secret` **in addition** to the `bearer-token` as a means of increased security.

That would be good in a sense that it increases the security of the whole process, but would be more cumbersome to set up the `bearer-token` connection, since you'll always need the client secret of that client.

Changing the client secret is then always a change on that application server, instead of having no dependency but the `bearer-token`, which would be no change on the application server required.


What I found searching:
- example of a `bearer-token` client (also using a client secret) https://github.com/stevenmaguire/oauth2-keycloak/issues/22
- a not complete example (which doesn't help) https://wjw465150.gitbooks.io/keycloak-documentation/content/authorization_services/topics/enforcer/keycloak-enforcement-bearer.html
- this one doesn't use a client secret https://groups.google.com/g/wildfly/c/-I0ICJm8CJI
- these guys do not need a client secret either https://blog.codecentric.de/2017/09/keycloak-und-spring-security-teil-1-einrichtung-frontend/
- this one used a secret, but I'm not sure if it was needed since he had another problem https://stackoverflow.com/questions/57804416/problem-calling-a-bearer-only-keycloak-endpoint-from-a-springboot-client-app

It feels like it could be possible...

**Comment by ferrerojosh** [comment]
Multi-tenancy service should only re-create the instance while changing only the `realm` and `secret`. So if `bearer-only` is set, every instance created should also be bearer only as seen here: https://github.com/ferrerojosh/nest-keycloak-connect/blob/81132009a70cf3b77a5d05d3dee267730846deb2/src/services/keycloak-multitenant.service.ts#L50-L54

The configuration options are injected and thus should be the same all throughout aside from the realm and secret:

https://github.com/ferrerojosh/nest-keycloak-connect/blob/81132009a70cf3b77a5d05d3dee267730846deb2/src/services/keycloak-multitenant.service.ts#L13-L16

When `keycloak.enforcer` is called, it is directly using the `request` object from NestJS as seen here:

https://github.com/ferrerojosh/nest-keycloak-connect/blob/81132009a70cf3b77a5d05d3dee267730846deb2/src/guards/resource.guard.ts#L129-L144

The library itself has a manual check for token validation so we can throw 401 errors natively but that's it. The processing for UMA tickets are done solely by the `keycloak-connect` library.

**Comment by KlausNie** [comment]
After working with it for a while, it seems like the right way to go is to have a client-secret for each realm (since keycloak requires that) and the backend service needs to keep that.
That makes it more secure: you need client secret and bearer token of that specific user to get access to the API.

I'm guessing it is that way so that keycloak endpoint cannot be queried/brute-forced by the public, but is only accessible from the service 🤷 

Thank you very much for your help! @ferrerojosh
