### ISSUE TITLE
Renew token?

### ISSUE THREAD

**Issue by vince-lynch** [ferrerojosh/nest-keycloak-connect#116]
Hi,

Is there a way to renew the token using the refresh_token? rather than just createGrant with the JWT?

Many thanks
Vince

**Comment by ferrerojosh** [comment]
Hello, token refresh should be handled by the client, not the application/resource server. (assuming a standard public facing client, and a resource server with client id and secret)

**Comment by vince-lynch** [comment]
> Hello, token refresh should be handled by the client, not the application/resource server. (assuming a standard public facing client, and a resource server with client id and secret)

sorry to ask for your help like this, but I noticed you had the `ensureFreshness` fn.

Currently getting a `REFRESH_TOKEN_ERROR`,
with the error claiming `invalid_token` 

After running the `grant` through the `ensureFreshness` but  
```
grant_type: refresh_token
client_auth_method: client-secret
```

this is when the access_token has expired and the refresh_token has several minutes left, in an OIDC SSO setup.

my main question is, when you wrote the `ensureFreshness` fn, how did you intend it to be used?
