### ISSUE TITLE
Registration Error

### ISSUE THREAD

**Issue by sgentile** [ferrerojosh/nest-keycloak-connect#117]
I'm attempting to add a setup as shown in the app.module
```
KeycloakConnectModule.registerAsync({
            useExisting: KeycloakConfigService,
            imports: [ConfigModule],
        }),
```

However I get this error:

Error: Nest can't resolve dependencies of the KEYCLOAK_CONNECT_OPTIONS (?). Please make sure that the argument KeycloakConfigService at index [0] is available in the KeycloakConnectModule context.

Potential solutions:
- If KeycloakConfigService is a provider, is it part of the current KeycloakConnectModule?
- If KeycloakConfigService is exported from a separate @Module, is that module imported within KeycloakConnectModule?
  @Module({
    imports: [ /* the Module containing KeycloakConfigService */ ]
  })

The KeycloakConnectModule module is part of nest-keycloak-connect

**Comment by dinbtechit** [comment]
Hi!  how did you resolve this error? I am running into the errror. Not sure what I am missing... :(
