### ISSUE TITLE
support @nestjs/graphql ^10.0.0

### ISSUE THREAD

**Issue by zoltan-mihalyi** [ferrerojosh/nest-keycloak-connect#120]
`@nestjs/graphql` peerDependency is set to `^6.0.0 || ^7.0.0 || ^8.0.0 || ^9.0.0`. Maybe updating this dependency will work out of the box

**Comment by ferrerojosh** [comment]
It should still work, since it highly depends on `@nestjs/graphql` without actually calling any apollo libraries. I'll update this in the next patch to just target `@nestjs/graphql@>=6`.
