### ISSUE TITLE
Nest can't resolve dependencies of the KEYCLOAK_CONNECT_OPTIONS (?). Please make sure that the argument KeycloakConfigService at index [0] is available in the KeycloakConnectModule context

### ISSUE THREAD

**Issue by isfand-apexe** [ferrerojosh/nest-keycloak-connect#122]
Node: 16.14.0
npm: 6.14.6

These are the errors I am getting while bootstrapping the app

<img width="1451" alt="Screenshot 2022-03-17 at 1 49 47 PM" src="https://user-images.githubusercontent.com/100771528/158791559-9842b7cf-6e85-4c99-91f4-1a54debf3759.png">
<img width="1006" alt="Screenshot 2022-03-17 at 1 50 31 PM" src="https://user-images.githubusercontent.com/100771528/158791583-aec20fb7-a6a2-4953-afe0-f8ba45df3b32.png">
<img width="719" alt="Screenshot 2022-03-17 at 1 53 05 PM" src="https://user-images.githubusercontent.com/100771528/158791590-81cb75b6-faaf-4a1f-9b69-8fd4d0a733d4.png">

**Comment by KlausNie** [comment]
I believe your `KeycloakConfigService` needs to be added to the providers. Might also be necessary to export it

**Comment by isfand-apexe** [comment]
@KlausNie I have created `KeycloakModule` and added `KeycloakService` in its `providers` and `exports`. But still getting that same error

**Comment by KlausNie** [comment]
If you have it in another module, make sure to export the Service in that module and add the module to the imports of the AppModule.

On another note: could you show us you `KeycloakConfigService`?

**Comment by isfand-apexe** [comment]
This is my `KeycloakService`
`import {
  KeycloakConnectOptions,
  KeycloakConnectOptionsFactory,
  PolicyEnforcementMode,
  TokenValidation,
} from 'nest-keycloak-connect';

import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

import { IKeycloakConfig } from '../config.service';

@Injectable()
export class KeycloakConfigService implements KeycloakConnectOptionsFactory {
  constructor(private config: ConfigService) {
    console.log(this.config.get<IKeycloakConfig>('keycloak'));
  }

  public createKeycloakConnectOptions(): KeycloakConnectOptions {
    const { authServerUrl, realm, clientId, secret } = this.config.get<IKeycloakConfig>('keycloak');

    console.log(authServerUrl, realm, clientId, secret);
    return {
      authServerUrl,
      realm,
      clientId,
      secret,
      policyEnforcement: PolicyEnforcementMode.PERMISSIVE,
      tokenValidation: TokenValidation.ONLINE,
    };
  }
}
`

This is my `KeycloakModule`

`import { Module } from '@nestjs/common';
import { KeycloakConfigService } from './keycloak-config.service';

@Module({
  providers: [KeycloakConfigService],
  exports: [KeycloakConfigService],
})
export class KeycloakConfigModule {}`

This is my `AppModule`

`import { KeycloakConnectModule, ResourceGuard, RoleGuard, AuthGuard } from 'nest-keycloak-connect';

import { Module } from '@nestjs/common';
import { APP_GUARD } from '@nestjs/core';
import { ConfigModule } from '@nestjs/config';

import { AppController } from './app.controller';

import { AppService, KeycloakConfigService, KeycloakConfigModule, configuration } from './services';

@Module({
  imports: [
    ConfigModule.forRoot({ load: [configuration] }),
    KeycloakConnectModule.registerAsync({
      useExisting: KeycloakConfigService,
      imports: [KeycloakConfigModule],
    }),
  ],
  controllers: [AppController],
  providers: [
    AppService,
    {
      provide: APP_GUARD,
      useClass: AuthGuard,
    },
    {
      provide: APP_GUARD,
      useClass: ResourceGuard,
    },
    {
      provide: APP_GUARD,
      useClass: RoleGuard,
    },
  ],
})
export class AppModule {}
`

**Comment by KlausNie** [comment]
I believe you have to add the `KeycloakConfigService` to the providers array of the `AppModule`.

Since the `KeycloakConfigService` is injected into the `KeycloakConnectModule.registerAsync` from the outside, you'd have to provide it from the outside. And that would then be the providers of the `AppModule`

**Comment by isfand-apexe** [comment]
Added the `KeycloakConfigService` to the providers array of `AppModule` as well. But nest-cli still gives the above error attached in the screenshot.

**Comment by KlausNie** [comment]
It could be that your `ConfigModule` needs to be globally accessible!
![image](https://user-images.githubusercontent.com/20414081/160398783-9130e199-7803-4ce8-a4d2-bb8b11bab0c6.png)

**Comment by ferrerojosh** [comment]
Issue seemed to be resolved I guess ?
