### ISSUE TITLE
realmSecretResolver async

### ISSUE THREAD

**Issue by On365** [ferrerojosh/nest-keycloak-connect#125]
is it possible to change this option so that the return can come from an async function? I made the change, to be able to put async but it's not getting the secret when it needs it.

multiTenant: {
        realmResolver: (request) => {
          console.log(`realmResolver:${request.get('host').split('.')[0]}`);
          return request.get('host').split('.')[0];
        },
        realmSecretResolver: async (realm) => {
          const account = await this.getSecret(realm); //database
          return account.client_secret;
        },
      },

**Comment by ferrerojosh** [comment]
This is a good enhancement. Thanks! This might break other users who don't use async so I'll implement it with a fallback.

**Comment by On365** [comment]
It worked. However, there is a question I would like to discuss with you.
If the Secret Key is only in the database for some reason, it does not reload the new one and continues validating with the old one. It only reloads if I restart the service.
Would it be possible to change it so that if it is not authorized it tries to get a new secret, or if that is not possible, could you create a configuration (allwaysLoadSecretKey) for it to always get the key?
<img width="866" alt="Captura de Tela 2022-04-20 às 08 26 28" src="https://user-images.githubusercontent.com/18447092/164220588-80006e3f-8902-477d-98dd-9cf7c889d32e.png">
