### ISSUE TITLE
realmSecretResolver async (don't reload secret key)

### ISSUE THREAD

**Issue by On365** [ferrerojosh/nest-keycloak-connect#126]
the issue #115 Works

However, there is a question I would like to discuss with you.
If the Secret Key is only in the database for some reason, it does not reload the new one and continues validating with the old one. It only reloads if I restart the service.
Would you create a configuration (reloadSecretKeyIfFail) so that if the validation fails, it tries to get a new secret, or if that is not possible, could you create a configuration (allwaysLoadSecretKey) for it to always get the key?

<img width="800" alt="Captura de Tela 2022-04-20 às 08 36 51" src="https://user-images.githubusercontent.com/18447092/164222141-d8b61a28-26d0-4729-9963-1dd6160a3c72.png">
<img width="945" alt="Captura de Tela 2022-04-20 às 08 34 07" src="https://user-images.githubusercontent.com/18447092/164221740-cdd7a178-6911-4b07-897f-977ad3b2238f.png">

**Comment by ferrerojosh** [comment]
Ah this is because a keycloak instance is created per realm, and if you want to change the secret key on the fly, it needs to create a new instance (in the case of multitenant, these instances are stored in memory), this is due to the project being an adapter of the official library.

I could allow a flag to always create a new instance but it'll always create a new keycloak instance and will probably hurt performance.

**Comment by On365** [comment]
Come on.

I'm new to JS/TS, but I've been programming for some time in delphi.

Since there is an instance created I made a motive to change this instance mediate to a configuration. I don't know the impact of this on the keycloak ecosystem or within its lib. But apparently resolves without having to create a new instance.

tell me what you think.
to be able to change it I had to fork it from your repository.

//Property
<img width="799" alt="Captura de Tela 2022-04-22 às 13 26 19" src="https://user-images.githubusercontent.com/18447092/164755848-877dac7a-e95e-45a6-a0b0-9313ef4b459d.png">

//Update the instance
<img width="1057" alt="Captura de Tela 2022-04-22 às 13 19 44" src="https://user-images.githubusercontent.com/18447092/164755556-febc2fef-d254-4c91-8eac-445572d7eca3.png">

//Result
<img width="849" alt="Captura de Tela 2022-04-22 às 13 30 39" src="https://user-images.githubusercontent.com/18447092/164756774-630bae5a-7222-422c-8278-5c8a2cbba82e.png">

**Comment by ferrerojosh** [comment]
If there is no issue with it, then we can go with this. Hopefully it doesn't have any side affects.

I'll make a change for this.

**Comment by madicnikola** [comment]
@ferrerojosh  @On365 

> If there is no issue with it, then we can go with this. Hopefully it doesn't have any side affects.
> 
> I'll make a change for this.

There's an issue with this approach:
When `multiTenant` and `realm` for `KeycloakConnectOptions` are not provided and they are in fact an optional config.
Meaning that we want to relay on library to resolve the realm and realmSecret based on claim for example `iss`.
 As in does in util.ts function: `useKeycloak` line 24: 
![image](https://github.com/ferrerojosh/nest-keycloak-connect/assets/36897908/d69de274-897b-4e83-b497-45f7900db418)
So removing this part of code that throws err when multiTenant opts not provided and making sure that  fallback to `this.keycloakOpts.secret` works should resolve it:
```
if (
      this.keycloakOpts.multiTenant === null ||
      this.keycloakOpts.multiTenant === undefined
    ) {
      throw new Error(
        'Multi tenant is not defined yet multi tenant service is being called.',
      );
    }
```
