### ISSUE TITLE
Roles Guard should merge "class" and "handler" roles !

### ISSUE THREAD

**Issue by medfata** [ferrerojosh/nest-keycloak-connect#127]
i think it would be great if we can just decorat the controller class with the roles decorator so that they apply to each method in it instead of repeating the decorator for each handler in the controller: 
by using nestjs reflector.getAllAndMerge instead of reflector.getAllAndOverride

**Comment by ferrerojosh** [comment]
This should be an option in the configuration. To avoid breaking other existing code.
