### ISSUE TITLE
Check user role manually

### ISSUE THREAD

**Issue by AlessandroStaffolani** [ferrerojosh/nest-keycloak-connect#134]
I'm trying to build a custom guard to verify that the logger user is the same asking for resources belonging to him. For example, if I have a resource `/users/alice/cats` I want to verify that alice is the current user. In addition, my custom guard should allow access to the resource if the user has role `admin`.

For the first step I simply use the user in the request and verify the param, here is the code:

```typescript
import { Injectable, CanActivate, ExecutionContext } from '@nestjs/common';
import { Observable } from 'rxjs';

@Injectable()
export class UserOwnedGuard implements CanActivate {
  canActivate(
    context: ExecutionContext,
  ): boolean | Promise<boolean> | Observable<boolean> {
    const request = context.switchToHttp().getRequest();
    const user = request.user;
    const userId = request.params.userId;
    return user.sid === userId;
  }
}
```

However, to verify the second step I need to get the token object from the grant and call the `hasRole` method. How can I inject the keycloak instance on my guard?

**Comment by ferrerojosh** [comment]
If you want the keycloak instance, inject it using the `KEYCLOAK_INSTANCE` provider

**Comment by ale8193** [comment]
Can you provide an example of how to properly inject the instance? 
I tried in the `app.module` (where I register the `KeycloakConnectModule`) to export the provider, but when I'm injecting the instance nest cannot resolve it.

I inject the instance like so:

```typescript
import {
  Injectable,
  CanActivate,
  ExecutionContext,
  Inject,
} from '@nestjs/common';
import { Observable } from 'rxjs';
import { KEYCLOAK_INSTANCE } from 'nest-keycloak-connect';
import { Keycloak } from 'keycloak-connect';

@Injectable()
export class UserOwnedGuard implements CanActivate {
  constructor(
    @Inject(KEYCLOAK_INSTANCE) private readonly keycloakInstance: Keycloak,
  ) {}

  canActivate(
    context: ExecutionContext,
  ): boolean | Promise<boolean> | Observable<boolean> {
    const request = context.switchToHttp().getRequest();
    const user = request.user;
    const userId = request.params.userId;
    return user.sid === userId;
  }
}
```

**Comment by ale8193** [comment]
Any updates on this?

**Comment by ferrerojosh** [comment]
This can now be done with the implementation of `@ConditionalScopes`.
