### ISSUE TITLE
@AuthenticatedUser undefined

### ISSUE THREAD

**Issue by Memo99** [ferrerojosh/nest-keycloak-connect#135]
Hi, 

when using the AuthenticatedUser decorator it is undefined. Could you give an example?

```
@Query(returns => User)
  @Public(false)
  async currentUser (
     @AuthenticatedUser() user : any
  ) : Promise<User>
{
    ...
   return user;
}
```

**Comment by Memo99** [comment]
okay solved it myself, you need to register the keycloak module also in the submodules.

**Comment by teuchezh** [comment]
can you provide more information? i have same issue.
