### ISSUE TITLE
Version 20 of keycloak-connect

### ISSUE THREAD

**Issue by smolinari** [ferrerojosh/nest-keycloak-connect#143]
Hi,

I see the peer dependency is currently only 19. Will this be increased soon now that version 20 of connect is out? 

Scott

**Comment by ferrerojosh** [comment]
I'll have to check if nothing breaks. If all is well, I can publish a new version for a peer update.

**Comment by Toilal** [comment]
I have upgraded to keycloak 20 without any problem on this dependency :+1:

**Comment by HaithamOumerzoug** [comment]
@ferrerojosh It's still not support version 20 for `https://www.npmjs.com/package/keycloak-connect`

**Comment by ferrerojosh** [comment]
Fixed in https://github.com/ferrerojosh/nest-keycloak-connect/commit/130f1b5dd4faaec80b0688027f68657292450938

**Comment by HaithamOumerzoug** [comment]
@ferrerojosh I really appreciate your support and guidance.Thank you !
