### ISSUE TITLE
Missing implementation for Resource-Based Authorization

### ISSUE THREAD

**Issue by anonrig** [ferrerojosh/nest-keycloak-connect#15]
According to the docs enforcer function can also have a claims function to define the resource URI's. Currently, nest-keycloak-connect doesnt provide the functionality.

```
      ​app.get('/protected/resource', keycloak.enforcer(['resource:view', 'resource:write'], {
         ​claims: function(request) {
           ​return {
             ​"http.uri": ["/protected/resource"],
             ​"user.agent": // get user agent  from request
           ​}
         ​}
       ​}), function (req, res) 
```

**Comment by anonrig** [comment]
More information can be found on https://www.keycloak.org/docs/latest/securing_apps/#_nodejs_adapter

**Comment by ferrerojosh** [comment]
I released an alpha build for this, feel free to make suggestions to the PR: #16 

```npm install nest-keycloak-connect@1.3.0-alpha.01```

Usage:
```typescript
import { Resource, Roles, Scopes, AllowAnyRole, Unprotected, Public } from 'nest-keycloak-connect';
import { Controller, Get, Delete, Put, Post, Param } from '@nestjs/common';
import { Product } from './product';
import { ProductService } from './product.service';

@Controller()
@Resource(Product.name)
export class ProductController {
  constructor(private service: ProductService) {}
    @Get()
    @ResourceConfig({
       claims: (request) => {
         return {
           "http.uri": ["/protected/resource"],
           "user.agent": // get user agent  from request
         }
       }
    })
    async findAll() {
      return await this.service.findAll();
    }
}
```

**Comment by anonrig** [comment]
Hey @ferrerojosh thank you for your fast response.

```javascript
@Controller('organization')
@Resource('organization')
export class OrganizationController implements OnModuleInit {
  constructor(private readonly adminProvider: KeycloakAdminService) {}

  @Get('/')
  // @Scopes('create')
  @EnforcerOptions({
    claims: request => {
      return {
        'http.uri': ['/organization/'],
        'user.agent': request.userAgent
      }
    }
  })
  async findAll() {
    return []
  }
```
Gives the following log:

[Nest] 5392   - 06/16/2020, 3:19:17 PM   [ResourceGuard] Protecting resource 'organization' with scopes: [ undefined ]

**Comment by anonrig** [comment]
My personal opinion is: We can get the http.uri and user.agent by default on the library side, and just skip the claims by default, but developer should have the ability to override it.

**Comment by anonrig** [comment]
With using it with Scopes, I'm having trouble getting a 200 response.

Logs:

[Nest] 5445   - 06/16/2020, 3:22:09 PM   [ResourceGuard] Protecting resource 'organization' with scopes: [ read ]
[Nest] 5445   - 06/16/2020, 3:22:09 PM   [ResourceGuard] Resource 'organization' denied to test-user.

```javascript
  @Get('/')
  @Scopes('read')
  @EnforcerOptions({
    claims: request => {
      return {
        'http.uri': ['/organization/'],
        'user.agent': request.userAgent
      }
    }
  })
  async findAll() {
    return []
  }
```

**Comment by ferrerojosh** [comment]
> 
> 
> My personal opinion is: We can get the http.uri and user.agent by default on the library side, and just skip the claims by default, but developer should have the ability to override it.

What it does is merely push additional claims to be evaluated in the keycloak server side. This depends on your authorization policies whether these additional claims will be evaluated or not.

So I for example can do:
```typescript
  @EnforcerOptions({
    claims: request => {
      return {
        'haveMoney': request.user.haveMoney,
      }
    }
  })
  async findAll() {
    return []
  }
```
And my keycloak realm has a policy that only permits any user claims that `haveMoney` with value of true.
> 
> 
> With using it with Scopes, I'm having trouble getting a 200 response.
> 
> Logs:
> 
> [Nest] 5445 - 06/16/2020, 3:22:09 PM [ResourceGuard] Protecting resource 'organization' with scopes: [ read ]
> [Nest] 5445 - 06/16/2020, 3:22:09 PM [ResourceGuard] Resource 'organization' denied to test-user.
> 
> ```js
>   @Get('/')
>   @Scopes('read')
>   @EnforcerOptions({
>     claims: request => {
>       return {
>         'http.uri': ['/organization/'],
>         'user.agent': request.userAgent
>       }
>     }
>   })
>   async findAll() {
>     return []
>   }
> ```

Is your keycloak realm configured properly ? With an `organization` resource and a policy (this is important) that allows users to have access to the `read` scope ?
