### ISSUE TITLE
keycloak-connect  peer dependence 

### ISSUE THREAD

**Issue by Gerthyy** [ferrerojosh/nest-keycloak-connect#151]
Hi, ferrerojosh
 i checked you last submit is not push to main. so you can try again submit. resolved peer Dependence keyclock-connect version > 10.  <21, The keycloak-connect  latest version > 21

**Comment by ferrerojosh** [comment]
Yeah I haven't made a release for the PR yet. It should be fine doing a forced install for now, you can ignore the peer dependency warning.

**Comment by Gerthyy** [comment]
Thanks for you answer.
