### ISSUE TITLE
Example realm json config no longer works on newer keycloak installations

### ISSUE THREAD

**Issue by ayushkamadji** [ferrerojosh/nest-keycloak-connect#154]
I get error when uploading example keycloak realm config from the example. The error is in relation to the removal of script upload policies. Reference: [here](https://github.com/keycloak/keycloak/issues/11664)

The fix is also in the reference. I can create a PR for the fix if needed.

**Comment by ferrerojosh** [comment]
Sure, if you want to make a PR go ahead. I'd appreciate it. Thanks.

**Comment by kasir-barati** [comment]
@ayushkamadji I also faced the same issue and I really appreciate it if you use docker. I do believe that creating a docker-compose file can relieve too many painful configurations.

Here you can see what I meant: https://github.com/ferrerojosh/nest-keycloak-connect/issues/153#issuecomment-1533668968

**Comment by ayushkamadji** [comment]
I'll PR sometime this weekend. If you need a workaround see the link I provided. 
Just need to remove some defaults from old kc version in the realm json file.

**Comment by ferrerojosh** [comment]
Resolved by #155
