### ISSUE TITLE
Question: export more internal functions 

### ISSUE THREAD

**Issue by svzieg** [ferrerojosh/nest-keycloak-connect#159]
Hey, 

we actually use this plugin and wrote some additional Services to support some authentication flows in our internal protocols.

But currently we need some internal logic like the "parseToken" function and the "keycloak-multitenant.service" in the util files which are not reexported by the default index.ts. Using the private files for importing however results in some strange resolution problems sometimes where node cannot find the files but they are there. 

Is it possible to export them as well, Or is there anything reason why they are not exported ? If possible, I would create a pull-request for this.

**Comment by ferrerojosh** [comment]
Well it should be possible to export them, they are internal for a reason since it might not find use outside, but if it fits your use case, why not ?
