### ISSUE TITLE
Question: What's the easiest way to get JWT data in unprotected endpoints?

### ISSUE THREAD

**Issue by andymel123** [ferrerojosh/nest-keycloak-connect#160]
**My (simplified) use case:**
I have an endpoint that can be used both with and without being logged in. If the user is not logged in, I use "anonymous" as username otherwise I want to retrieve the username from the token.

**Example:**
```
@Public()
async create(@AuthenticatedUser() jwtData: any): Promise<...> {
  
  const username = jwtData == null ? 'anonymous' : jwtData...;
  ...
}
```

**Is there a "nest-keycloak-connect way" of getting the JWT data in public endpoints?** 
In the above construct (@ Public and @AuthenticatedUser() combined) the user is always undefined as the auth.guard is skipped.

I could read and parse the token myself but it would be more consistent to use nest-keycloak-connect to do it. 

Any recommendation to fulfill the use case without re-writing the code? Seems like the specific logic in the library is not exported/public.

- [extractJwt](https://github.com/ferrerojosh/nest-keycloak-connect/blob/5b9a642bb6030ba61730f4e8fe4542f8000bdd09/src/guards/auth.guard.ts#L155)
- [validateToken](https://github.com/ferrerojosh/nest-keycloak-connect/blob/5b9a642bb6030ba61730f4e8fe4542f8000bdd09/src/guards/auth.guard.ts#L111)
- [parseToken](https://github.com/ferrerojosh/nest-keycloak-connect/blob/5b9a642bb6030ba61730f4e8fe4542f8000bdd09/src/util.ts#L59)

**Comment by andymel123** [comment]
I am still interested in getting an answer here :)

**Comment by ferrerojosh** [comment]
You can pass a boolean of false in the `@Public` decorator.

```typescript
@Public(false)
async create(@AuthenticatedUser() jwtData: any): Promise<...> {
  
  const username = jwtData == null ? 'anonymous' : jwtData...;
  ...
}
```
