### ISSUE TITLE
Validate token for API

### ISSUE THREAD

**Issue by Xeyos88** [ferrerojosh/nest-keycloak-connect#161]
Good morning,
I am writing here for support.
I am trying to create a back-end that exposes some rest API protected.

I created a small test project that is very similar to the example project here, except for the Product part (so I removed ResourceGuard as well).

The problem is that I'm trying to call a protected API with a token generated by a front-end application that authenticates smoothly on the same client, but I keep getting 401s.

Also, I would like to figure out how to insert a service in between, to generate a User object from the token, which I can then save.

Thanks in advance.

**Comment by ferrerojosh** [comment]
I am confused, you only need the authentication part for your service right ?
