### ISSUE TITLE
Postman example errors and other suggestions

### ISSUE THREAD

**Issue by TheFern2** [ferrerojosh/nest-keycloak-connect#164]
The postman example url in the prescript needs to be updated, auth isn't needed in the url anymore. In addition adding PORT as variable might be useful in case you're not running in 8080. An env in the example might also help to avoid having the port hardcoded. I know is an example just leaving these as suggestions. I can make if PR if maintainers are interested in these changes.

**Comment by ferrerojosh** [comment]
You can leave a PR if you want to. I haven't updated the example project for quite a while now.
