### ISSUE TITLE
Multi tenant configuration: realmAuthServerUrlResolver

### ISSUE THREAD

**Issue by sbabych** [ferrerojosh/nest-keycloak-connect#174]
Hello, 

official `keycloak-connect` library has an issue related to the FrontendURL and the issuer validation. 
[Allow multiple auth-server-urls](https://github.com/keycloak/keycloak-nodejs-connect/issues/480)
[Supporting different ISS when validating token](https://github.com/keycloak/keycloak-nodejs-connect/issues/308)

What do you think about idea to extend current Multi tenant configuration with new resolver: `realmAuthServerUrlResolver`
This resolver will change `keycloak.grantManager.realmUrl` and will help to bypass `keycloak-connect` library issues 

Right now to achieve this I need to implement my own KeycloakMultiTenantService and override method: 
`get(realm: string): Promise<KeycloakConnect.Keycloak>;`

Thank you!

**Comment by ferrerojosh** [comment]
You can make a PR for it and I can make a review, since you already extending and implementing your own.
