### ISSUE TITLE
Question :Error Wrong ISS between keycloak and nestjs app container

### ISSUE THREAD

**Issue by DimRX** [ferrerojosh/nest-keycloak-connect#176]
Hello,

I currently have a docker architecture with a nginx that serves as a reverse proxy, a nestjs backend and a keycloak, each on different containers and on the same network.

When I make an api request from my frontend, I give a jwt token from the frontend to the backend. But the backend returns this error: 

WARN [Keycloak] Cannot validate access token: Error: Grant validation failed. Reason: invalid token (wrong ISS)

Note that I've configured my nginx with my domain name and SSL certificates.

Extract from my configuration on my nestjs backend
authServerUrl: "https://keycloak.domain.name",
realm: "real-name",
clientId: "client-id",
secret: "secret"

Thanks in advance for your help

**Comment by DimRX** [comment]
Update: I've added a log that prints the contents of "keycloak.grantManager",

![bug1](https://github.com/ferrerojosh/nest-keycloak-connect/assets/46445439/87e5f86a-e738-45ec-bc66-d2b9046e50f8)

Is it normal to have a clientId and secret undefined knowing that I specify them as shown on the screen below?

![bug2](https://github.com/ferrerojosh/nest-keycloak-connect/assets/46445439/108f3d6b-e1ab-4b43-accd-26789405787a)


.env :

KEYCLOAK_REALM='realm-name'
KEYCLOAK_CLIENT_ID='realm-client-id'
KEYCLOAK_BASE_URL='https:/domain-name'
KEYCLOAK_SECRET='secret'

**Comment by DimRX** [comment]
Update : 

J'ai ajouté en dur mes variables pour keycloak dans le code et j'ai désormais des valeurs pour mon realm et ma baseUrl cependant j'ai désormais une nouvelle erreur qui apparaît :

![bug3](https://github.com/ferrerojosh/nest-keycloak-connect/assets/46445439/762dfe2e-9718-4cda-8494-643c067ce44f)


Est-il possible de spécifier la clé public ?

**Comment by ferrerojosh** [comment]
Related to #174.

**Comment by moisesrodriguez** [comment]
I'm having the `invalid token (wrong ISS)` error. I've read this issue and the fix to #174 in https://github.com/ferrerojosh/nest-keycloak-connect/commit/43977c74e42e457261b9120730f59c7e6cd4fca7. But it is not clear to me how to implement the fix in order to fix `wrong ISS` error.

Pointers would be appreciated.

**Comment by whitebiker** [comment]
This problem has been around for 2 years - it is crucial for the integration of Keycloak into NestJS. However, the authors, for some reason, do not want to solve it. What a shame.

**Comment by hikufi-dev** [comment]
My issue what that for `authServerUrl` I was pointing it to `http://localhost:8080/auth` but for newer versions of Keycloak it is `http://localhost:8080`

**Comment by moisesrodriguez** [comment]
I'm able to run it in my local machine with `authServerUrl: http://localhost:8080`, but once I'm trying with production and I have `authServerUrl: https://domain.com` I get `invalid token (wrong ISS)`. The only difference between local and prod is that I have a nginx reverse proxy to terminate SSL. @DimRX  where you able to figure it out?

**Comment by ferrerojosh** [comment]
> I'm able to run it in my local machine with `authServerUrl: http://localhost:8080`, but once I'm trying with production and I have `authServerUrl: https://domain.com` I get `invalid token (wrong ISS)`. The only difference between local and prod is that I have a nginx reverse proxy to terminate SSL. @DimRX where you able to figure it out?

I'll try to replicate this using my own domain, I have lots of free time now so I can work back on this oss project.

**Comment by moisesrodriguez** [comment]
@ferrerojosh I'll be honest I was able to get rid of the error `invalid token (wrong ISS)` and I am using it like the example I wrote `authServerUrl: https://auth.domain.com` for my production env. But I do not remember what was the root problem for getting rid of that error.

My conf looks like:

``` typescript
KeycloakConnectModule.registerAsync({
      imports: [ConfigModule],
      useFactory: async (configService: ConfigService) => ({
        authServerUrl: configService.get<string>("keycloak.authServer"),
        realm: configService.get<string>("keycloak.realm"),
        clientId: configService.get<string>("keycloak.clientId"),
        secret: configService.get<string>("keycloak.secret"),
        realmPublicKey: configService.get<string>("keycloak.publicKey"),
        policyEnforcement: PolicyEnforcementMode.PERMISSIVE,
        tokenValidation: TokenValidation.OFFLINE,
        cookieKey: "KEYCLOAK_JWT",
      }),
      inject: [ConfigService],
})
```

**Comment by DimRX** [comment]
Hello, I managed to avoid the problem by switching the tokenValidation to Offline. Here is my configuration :

`KeycloakConnectModule.register({
      authServerUrl: process.env.KEYCLOAK_BASE_URL,
      realm: process.env.KEYCLOAK_REALM,
      clientId: process.env.KEYCLOAK_CLIENT_ID,
      secret: process.env.KEYCLOAK_CLIENT_SECRET,
      realmPublicKey: process.env.KEYCLOAK_REALM_PUBLIC_KEY,
      tokenValidation: TokenValidation.OFFLINE,
      bearerOnly: true,
    })`
   
 My keycloak is behind a reverse proxy nginx with a valid SSL certificate

**Comment by ferrerojosh** [comment]
This is due to the fact that keycloak has removed `/auth` for their auth server url. The `invalid token (wrong ISS)` error comes up whenever the `authServerUrl + '/realm/' + realm` does not match the `(iss)` issuer claim.

So if you are in a reverse proxy, make sure you set your auth server urls to the domain you are actually using.
