### ISSUE TITLE
Update peerDependencies of keycloak-connect version to 24.0.1

### ISSUE THREAD

**Issue by juergenzimmermann** [ferrerojosh/nest-keycloak-connect#177]
Despite the package keycloak-connect is deprecated, the team goes on fixing minor bugs. And its version number follow the keycloak main version number. I suggest to upgrade the peerDependencies version to 24.0.1: https://www.keycloak.org/docs/24.0.1/release_notes and https://github.com/keycloak/keycloak-nodejs-connect/releases.

**Comment by ferrerojosh** [comment]
Closed in d9997f5cfb5add01bf8236c47ffae234e2fa36c2
