### ISSUE TITLE
JWT in cookieKey doesn't work for ResourceGuard 

### ISSUE THREAD

**Issue by patostickar** [ferrerojosh/nest-keycloak-connect#178]
As the title mentions, if you don't send the Access JWT as a Bearer Token in the Headers, the internal `const isAllowed = yield enforcerFn(keycloak, permissions);` returns false even if you are allowed to use the resource. I sent the same JWT in the headers, and it works fine.

This behavior doesn't happen with AuthGuard and RoleGuard.

**Comment by ferrerojosh** [comment]
I'll check on it.

**Comment by ferrerojosh** [comment]
Are you using keycloak's authz feature ? If not properly configured, it will always return false.

**Comment by patostickar** [comment]
Hi, thank you for the reply. Yes, we did a simple authorization
configuration (resource, scope, policy, permission) and it works as
expected when we send the access token as a Bearer token, and it denies
everything when it comes from the cookie.

I'll try to find time and provide a working example.

**Comment by ferrerojosh** [comment]
Oh you're right, its because the keycloak enforcer only looks for the token in the headers, I'll have to manually attach the one in the cookie to the authorization header then.

**Comment by patostickar** [comment]
Thank you John 🙂

**Comment by biryusal** [comment]
Hi, guys!

Are you sure that the JWT cookie works for the AuthGuard?
I guess it doesn't work for this guard either.

I tried to use `KEYCLOAK_JWT` from the documentation as the `cookieKey`, but it didn't work — the service doesn't even log anything.

However, when I pass the same value that I was passing in a cookie to a `Bearer Authorization header`, it works fine!

`/auth-utils/config.js` from `keycloak-nodejs-connect` also doesn't have a `cookieKey`.

[GitHub link](https://github.com/keycloak/keycloak-nodejs-connect/blob/main/middleware/auth-utils/config.js)

**Comment by biryusal** [comment]
It would be fine I would be able to pass the token in the cookies, because then it won't be necessary to fetch the token on the client-side

**Comment by ferrerojosh** [comment]
> Hi, guys!
> 
> Are you sure that the JWT cookie works for the AuthGuard? I guess it doesn't work for this guard either.
> 
> I tried to use `KEYCLOAK_JWT` from the documentation as the `cookieKey`, but it didn't work — the service doesn't even log anything.
> 
> However, when I pass the same value that I was passing in a cookie to a `Bearer Authorization header`, it works fine!
> 
> `/auth-utils/config.js` from `keycloak-nodejs-connect` also doesn't have a `cookieKey`.
> 
> [GitHub link](https://github.com/keycloak/keycloak-nodejs-connect/blob/main/middleware/auth-utils/config.js)
> 
> It would be fine I would be able to pass the token in the cookies, because then it won't be necessary to fetch the token on the client-side

What we are doing is fooling the library to think we have a Bearer token attached to the header, in which we don't. We just simply grab the token from the cookie and attach it to the request headers as a bearer token.

Of course there is a confirmed bug in which it doesn't happen for the enforcer and I will be fixing it in the meantime.

**Comment by rohanshah000x7** [comment]
I also encountered this problem, but I solved it
You have to install `cookie-parser` and add `app.use(cookieParser())` to your application by your own, or the library won't be able to read the cookies from request and they'll be `undefined`
You can read more about that here:
https://docs.nestjs.com/techniques/cookies

And, I guess, @ferrerojosh  you should add this to the `README.md` file, because it's not obvious, as for me, and should be added to the `FAQ`, for example
