### ISSUE TITLE
Configuration of Role-based authentication

### ISSUE THREAD

**Issue by MarcBollmann** [ferrerojosh/nest-keycloak-connect#19]
Hello I configured 'nest-keycloak-connect' and some endpoints with Role-based authentication. Everytime I try to do the actual api-call via swagger I get a 403 Forbidden Ressource Error. 

What are the exact configurations you have to do in Keycloak?
I created a role (I tried realm and client role) and added my user to it. If I use the @AllowAnyRole()-decorator it works fine, thats why I think this could be a configuration issue. @ferrerojosh

**Comment by MarcBollmann** [comment]
Client role:
![grafik](https://user-images.githubusercontent.com/25687814/88653202-0db39480-d0cc-11ea-8cd6-7f5a34ea3e5d.png)

Realm role:
![grafik](https://user-images.githubusercontent.com/25687814/88653358-3d629c80-d0cc-11ea-8fe7-6d355e3784b4.png)


My User:
![grafik](https://user-images.githubusercontent.com/25687814/88653461-671bc380-d0cc-11ea-85cb-fc89d4ad5461.png)

**Comment by SalahAdDin** [comment]
@MarcBollmann How did you solve this?

**Comment by MarcBollmann** [comment]
@SalahAdDin I think the fault was that swagger doesn't support redirections try paste the api request in your browser address bar!

**Comment by SalahAdDin** [comment]
@MarcBollmann well, i'm working with **GraphQL** and i can't make it work.
