### ISSUE TITLE
Disable logs on terminal and connect a log watcher

### ISSUE THREAD

**Issue by JoaoMarcos160** [ferrerojosh/nest-keycloak-connect#191]
Is it possible to disable logs for development environments? Or connect a log watcher like Sentry or New Relic and not log to the terminal?

**Comment by ferrerojosh** [comment]
The library is using the standard nestjs logger, you could just override that. See: https://docs.nestjs.com/techniques/logger

**Comment by JoaoMarcos160** [comment]
But by changing it this way, would I change the entire API? Would it be possible to change just the auth logs?

**Comment by ferrerojosh** [comment]
No, nest should be able to capture that you are using your own custom logger.

**Comment by ferrerojosh** [comment]
This will be changed with the 2.0 release, as it is a breaking change.
