### ISSUE TITLE
How to get user id in controller?

### ISSUE THREAD

**Issue by teaknig** [ferrerojosh/nest-keycloak-connect#192]
In my case, the @KeycloakUser decorator isn't working for some reason

![image](https://github.com/user-attachments/assets/156fa77f-c4ae-4043-9baa-b6d052c3c13c)

versions: 

```json
    "keycloak-connect": "^26.0.1",
    "nest-keycloak-connect": "^1.10.1",
```

**Comment by ferrerojosh** [comment]
> In my case, the @KeycloakUser decorator isn't working for some reason
> 
> ![image](https://private-user-images.githubusercontent.com/34206915/379233931-156fa77f-c4ae-4043-9baa-b6d052c3c13c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMDIzMTksIm5iZiI6MTczMDAwMjAxOSwicGF0aCI6Ii8zNDIwNjkxNS8zNzkyMzM5MzEtMTU2ZmE3N2YtYzRhZS00MDQzLTliYWEtYjZkMDUyYzNjMTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDA0MDY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NGM0MzU2NjBjZDYzZTJhZjMzZDU1ZjhlZWYzMTc1MjExMjE5YTEwNzZjZWU4MDg0MDZlOTY4N2ZiMTdhYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kg3tAWa7vlj1CykqNbgzfQ_8Mj7AO8uoATI_JYwUgho)
> 
> versions:
> 
> ```json
>     "keycloak-connect": "^26.0.1",
>     "nest-keycloak-connect": "^1.10.1",
> ```
v2.0 is not yet released yet, I forgot to change the default branch to show 1.0, my bad.

**Comment by teaknig** [comment]
Thank you very much
