### ISSUE TITLE
keycloak 11 & nest-keycloak-connect 1.3.0-alpha.3 - fail to get 200 with roles

### ISSUE THREAD

**Issue by stackatom** [ferrerojosh/nest-keycloak-connect#22]
Hi,

I'm trying to make this project work with latest keycloak docker instance (currently version 11.x).

Using a fresh nestjs project with latest nest-keycloak-connect i'm using the following code : 

```
@Controller()
@Resource('admin')
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get('admin')
  @Roles('admin')
  getHello(): string {
    return this.appService.getHello();
  }
}
```

I have setup a keycloak custom realm, with a scope "admin" and a role "admin" under it.
Here is the decoded jwt I try to pass to the app : 

```
{
  "exp": 1598143670,
  "iat": 1598143370,
  "jti": "f5b80827-0573-4710-a548-14ace94d1473",
  "iss": "http://localhost:8080/auth/realms/testproject",
  "sub": "e85763bd-281a-4fca-86a0-f7afcaaf46d2",
  "typ": "Bearer",
  "azp": "admin-cli",
  "session_state": "e7b4e27b-8cba-4124-9d41-c1659ceeec23",
  "acr": "1",
  "realm_access": {
    "roles": [
      "admin"
    ]
  },
  "scope": "email admin roles profile",
  "email_verified": true,
  "name": "admin",
  "preferred_username": "admin",
  "given_name": "admin",
  "family_name": "admin",
  "email": "admin@admin.com"
}
```

I also try to add   @Scopes('admin'), without much more success.

Do I miss something ? Which version of keycloak is supported by this lib ? 

Thanks for your help.

**Comment by ferrerojosh** [comment]
`Resource` and `Scopes` are part of Keycloak's Authorization and Services (AuthZ)

Your Keycloak server needs to be properly setup in order for this to work. Please see https://www.keycloak.org/docs/latest/authorization_services/ for more information regarding this.

As for the roles, by default it will use the roles ***within your application***, if you want to use realm roles, follow the format `"realm:myrole"`

**Comment by ferrerojosh** [comment]
Tickets like this seems to be more rampant, I'll soon be putting up a proper example project so people won't get confused later on.

**Comment by ferrerojosh** [comment]
As for the keycloak version supported by this lib, as of writing it currenly supports `keycloak-connect@^9.0.0`

**Comment by colorado-nate** [comment]
Any guesses when keycloak 11 support will be released?

**Comment by ferrerojosh** [comment]
> Any guesses when keycloak 11 support will be released?

I'll check if there are any breaking changes, then I'll do a release
