### ISSUE TITLE
OptionalUnprotected decorator

### ISSUE THREAD

**Issue by BoKKeR** [ferrerojosh/nest-keycloak-connect#24]
Is there a way to have a single endpoint work with authenticated users, and no authenticated users? Without stripping away the authorization header?

I have a few use cases. For the commentSection, we have a single endpoint where we fetch the comments, not logged in users should be able to fetch comments. But when a user is logged in, the same endpoint should be usable, but it should also pass in the user object to the controller. Like this, we can have one endpoint that does multiple things based on if the user is logged in or not.

Not logged in user fetches comment:
```
{
  "_id": "LhNuJd15_X7",
  "author": "e3fc0911-b708-481e-b4fb-8c1c60a57c3d",
  "text": "test comment !",
  "isOwnComment": false
}
```

Logged in `user1` fetches comment:
```
{
  "_id": "LhNuJd15_X7",
  "author": "e3fc0911-b708-481e-b4fb-8c1c60a57c3d",
  "text": "test comment !",
  "isOwnComment": true
}

```

This is a code I used with passport to create a decorator that would let users still query the endpoint even if they are not logged in, but it would provide the user object in the header.
```
import {
  createParamDecorator,
  ExecutionContext,
  Injectable,
} from '@nestjs/common'
import { AuthGuard } from '@nestjs/passport'
import { User } from '../user/user.model'

export const GetUser = createParamDecorator(
  (data, ctx: ExecutionContext): User => {
    const req = ctx.switchToHttp().getRequest()
    return req.user
  }
)

@Injectable()
export class AuthOptionalGuard extends AuthGuard('jwt') {
  async canActivate(context: any) {
    await super.canActivate(context)
    return true
  }

  handleRequest(err, user, info, context) {
    try {
      super.handleRequest(err, user, info, context)
    } catch (e) {
      // console.log(e)
    }
    if (user) {
      return user
    }
  }
}
 
```
 is there a way to have similar functionality in this package? Right now when using `@Unprotected` strips away the authorization header when a logged-in user requests the endpoint.

**Comment by ferrerojosh** [comment]
No need for an additional decorator for this, I'll be adding a `skipAuth `parameter to the readily-available `@Unprotected/@Public` decorators.
