### ISSUE TITLE
keycloak config differ from the one provided by keycloak server

### ISSUE THREAD

**Issue by jbpin** [ferrerojosh/nest-keycloak-connect#31]
Keycloak nodejs lib allow user to configure the connection using a JSON File (keycloak.json) or in copy paste from the admin console. https://www.keycloak.org/docs/latest/securing_apps/#usage-2

Here is the source code for this. 
https://github.com/keycloak/keycloak-nodejs-connect/blob/f8e011aea5/middleware/auth-utils/config.js

Can we align the https://github.com/ferrerojosh/nest-keycloak-connect/blob/master/src/interface/keycloak-connect-options.interface.ts to reflect the same structure ?

**Comment by ferrerojosh** [comment]
I could officially follow the typings here: https://github.com/keycloak/keycloak-nodejs-connect/blob/master/keycloak.d.ts

But for more flexibility, I'll follow the javascript version of the code.
