### ISSUE TITLE
Expose the KEYCLOAK_INSTANCE constant

### ISSUE THREAD

**Issue by RogierdeRuijter** [ferrerojosh/nest-keycloak-connect#32]
Hello!

I would like to use the `KEYCLOAK_INSTANCE` constant so I can inject the Keycloak instance in my application. 

Like this:
```ts
import { KEYCLOAK_INSTANCE } from 'nest-keycloak-connect';

constructor(@Inject(KEYCLOAK_INSTANCE) private keycloak: KeycloakConnect.Keycloak) {}
```

Exposing the KEYCLOAK_INSTANCE constant through the library interface is that something you would like to do? If yes, I could make a PR for it.

Cheers

**Comment by shirish87** [comment]
+1

This would be useful in my case for implementation of a custom role guard. In addition to `KEYCLOAK_INSTANCE`, some of the decorator constants (META_SKIP_AUTH, etc.) may also be useful to expose.

atm, I get around this by copying over constants from the library into a file.

Either public constants or some sort of base `AuthGuard` with helpers would go a long way.

Thanks!

![image](https://user-images.githubusercontent.com/304687/102999725-98030600-454f-11eb-8989-6691ebb3c55e.png)

**Comment by ferrerojosh** [comment]
I have no issues regarding this. It promotes a little bit of extensibility like custom guards.

PRs are welcome. I'll release this along with the next minor version.

**Comment by RogierdeRuijter** [comment]
Love it thanks!

**Comment by SantoshKumarSubedi** [comment]
I am trying to inject KEYCLOAK_INSTANCE in services but It always shows the same error. 

![image](https://user-images.githubusercontent.com/20809800/113186730-be83bc00-9277-11eb-931d-01fd008b21bb.png)

I have register KeycloakConnectModule in _app.module.ts_ as shown in the DEMO and imported it in _users.module.ts_ as well. 

I may be missing something here but i am new to nest so any help will be appreciated.
