### ISSUE TITLE
Request support for Keycloak 12

### ISSUE THREAD

**Issue by colorado-nate** [ferrerojosh/nest-keycloak-connect#36]
Keycloak-connect 12.0.1 and keycloak 12.0.1 have been released.  Are there plans to support this newer version?  Thanks!

**Comment by stingalleman** [comment]
I also have this question.

**Comment by tillsanders** [comment]
I, too, need this, so I cloned the repo and started looking for the things that would need updating. I'm far from being an expert on nest, keycloak or this plugin, but as far as I can see, there isn't much to do. I actually managed to get it working only by updating the `keycloak-connect` dependency to the latest version. So far, it works as expected 👍

**Comment by tillsanders** [comment]
I'm on a tight schedule with this project, so I forked this module, made a build with the latest version of `keycloak-connect` and published that to the GitHub NPM Registry: https://github.com/tillsanders/nest-keycloak-connect/packages/582546

If any of you might need this too, you can install  it by first adding this to your project's `.npmrc`:

```
@tillsanders:registry=https://npm.pkg.github.com/
```

Then install it like this:

```sh
npm install @tillsanders/nest-keycloak-connect@1.5.1
```

Make sure to update your imports and be aware, that this is only a temporary fork. I hope we can update the main project quite as easily soon.

**Comment by ferrerojosh** [comment]
Will make a small change for this.
