### ISSUE TITLE
Secret key

### ISSUE THREAD

**Issue by SergKozyrev** [ferrerojosh/nest-keycloak-connect#37]
Hi, why in keyckloak config secret is required? In keycloak-connect is not required. 
What should i do if my client is public?

**Comment by tillsanders** [comment]
I needed to figure this out, too. Maybe this article will help you: https://chamith.medium.com/secure-front-end-react-js-and-back-end-node-js-express-rest-api-with-keycloak-daf159f0a94e

I set up two separate clients: a public one for the frontend and a bearer-only one for the backend.

**Comment by SergKozyrev** [comment]
> I needed to figure this out, too. Maybe this article will help you: https://chamith.medium.com/secure-front-end-react-js-and-back-end-node-js-express-rest-api-with-keycloak-daf159f0a94e
> 
> I set up two separate clients: a public one for the frontend and a bearer-only one for the backend.

**Comment by SergKozyrev** [comment]
@tillsanders , thank you for the article, but I can use only public clients for the backend. With keycloak-express, i can do it, but I want to use nestJs and really don't understand why secret is required.

**Comment by tillsanders** [comment]
I see. Well, to answer your question, this plugin seems to rely solely on JWT to authenticate users (see [here](https://github.com/ferrerojosh/nest-keycloak-connect/blob/master/src/guards/auth.guard.ts#L60)) and for that it has to have a shared secret with the server. That won't help you, but at least that is the reason why the secret is required.

May I ask why you can only use public clients for the backend?

**Comment by SergKozyrev** [comment]
Thank you for helping, it looks like I should use other solutions. I need public clients because I create clients dynamically.

**Comment by ferrerojosh** [comment]
Thanks for this. I forgot I changed the config and still required a secret.

**Comment by ferrerojosh** [comment]
But having no secret will disable the Keycloak AuthZ function, hence it will be a problem for this library which is built around that. It might be better to use bearer-only using [passport](https://github.com/jaredhanson/passport) since a keycloak server will fully support it since it uses the OAuth 2.0 standard.

If I find good way to make this work as bearer-only, I'll be reopening this issue. But for authenticating using the claims in a bearer-token, please use Passport.

**Comment by vk-detrans** [comment]
If someone is looking for a bearer-only approach, I found [this blog post](https://itnext.io/protecting-your-nestjs-api-with-keycloak-8236e0998233) useful. Thanks @paztek

**Comment by valerii15298** [comment]
@ferrerojosh hello. Any updates on this one?
I am using this config
```
{
  "realm": "myrealm",
  "bearer-only": true,
  "auth-server-url": "https://auth.mywebsite.com/auth/",
  "ssl-required": "all",
  "resource": "backend",
  "confidential-port": 0
}
```
But `secret` is required. What value should I provide for the secret?
And should I use this secret field at all?
I am using last version of "nest-keycloak-connect": "^1.9.0",

**Comment by vk-detrans** [comment]
@valerii15298 could you please try this? Use the above config and have empty string as `secret` if you only want to verify bearer token.

**Comment by valerii15298** [comment]
@vk-detrans thanks you very much for such a quick response. And what do you mean by `only verify bearer token` ?

I need also all my guards, Roles and other decorators to work properly.

**Comment by vk-detrans** [comment]
@valerii15298 I didn't check that part, but I think we get the roles info in the JWT.

> what do you mean by `only verify bearer token` ?

I meant the `keycloak-connect`'s option
```json
"bearer-only": true,
```

I found that we don't need this when we use offline token validation.

Please try and update 🙂
