### ISSUE TITLE
Forbidden resource with GraphQL

### ISSUE THREAD

**Issue by SalahAdDin** [ferrerojosh/nest-keycloak-connect#38]
I have one day trying to authenticate a **GraphQL** mutation without any success:
```typescript
@Mutation((returns) => UsersType)
  @Roles('host', 'erasmus')
  createUser(@Args('createUserInput') createUserInput: CreateUserInput) {
    return this.usersService.createUser(createUserInput);
  }
```

I request the **JWT** token and i pass it ass a bearer token, it contains the required rol:
```json
"typ": "Bearer",
  "azp": "macondo/frontend",
  "acr": "1",
  "realm_access": {
    "roles": [
      "offline_access",
      "host",
      "uma_authorization"
    ]
  },
  "resource_access": {
    "macondo/backend": {
      "roles": [
        "host"
      ]
    },
    "macondo/frontend": {
      "roles": [
        "host"
      ]
    },
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "email profile",
  "email_verified": true,
  "preferred_username": "userhost",
  "locale": "tr"
```

The **Keycloak** settings are:
```typescript

    KeycloakConnectModule.register({
      realm: process.env.KEYCLOAK_REALM,
      bearerOnly: true,
      authServerUrl: process.env.KEYCLOAK_SERVER_URL,
      clientId: process.env.KEYCLOAK_CLIENT_ID,
      secret: process.env.KEYCLOAK_SECRET,
      // cookieKey: 'KEYCLOAK_JWT',
    }),
```
where:
```env
KEYCLOAK_CLIENT_ID=macondo/backend
KEYCLOAK_REALM=macondo
KEYCLOAK_SECRET=6cb0f7cb-38a4-4294-948b-b819bca69dd5
KEYCLOAK_SERVER_URL=http://localhost:8080/auth
```

At playground i try:
<img width="1440" alt="Screen Shot 2021-02-09 at 23 42 07" src="https://user-images.githubusercontent.com/5034215/107426613-8098d000-6b31-11eb-85fa-6586d2378cf8.png">

As you can see it does not get access to the resources.

Is use the unprotected or allow any rule decorator it works fine.

What's the missing thing here? Thank you very much.

**Comment by ferrerojosh** [comment]
Use AllowAnyRole decorator, the Roles decorator are using 'AND' and adding AllowAnyRole makes it into an 'OR'.

I think I need to revise the decorators.

**Comment by SalahAdDin** [comment]
@ferrerojosh yeah, you are right about it. Can you provide us a very good documentation about decorators where we can learn how to use it? or, Can you improve this package documentation to make us easier to understand this decorators?

Thank you
