### ISSUE TITLE
Roles decorator

### ISSUE THREAD

**Issue by driesvancraen** [ferrerojosh/nest-keycloak-connect#4]
Hi,

The documentation on NPM speaks about a Roles decorator.
But it is nowhere to be found.
Is it possible to have this working?

**Comment by ferrerojosh** [comment]
Which documentation ? I do not remember having a Roles decorator, only Resource and Scopes

**Comment by driesvancraen** [comment]
I just realized it was a fork on NPM that directed to your original repo. My bad!
https://www.npmjs.com/package/@cenkce/nest-keycloak-connect
