### ISSUE TITLE
Is there a way to disable token ISS validation?

### ISSUE THREAD

**Issue by lieberlois** [ferrerojosh/nest-keycloak-connect#40]
Is there a way to disable the ISS validation of the token? This is possible with typical Keycloak Libraries for .NET and required for some setups (especially in development)!

**Comment by ferrerojosh** [comment]
Not that I know of, this is an adapter for the official keycloak nodejs library, I [dug around](https://github.com/keycloak/keycloak-nodejs-connect/blob/f8e011aea5021b81cd085df078eee7b5d773d0cc/middleware/auth-utils/grant-manager.js#L428) and there seemed to be no way to disable it.

**Comment by EFritzsche90** [comment]
I have the same problem while running on Kubernetes. I just forked the official Keycloak project and removed the issuer check, just to make it running.

Btw: Is the logging working for you within the catch:

`
    try {      const result = await this.keycloak.grantManager.validateAccessToken(jwt);
      if (typeof result === 'string') {        // Attach user info object        request.user = parseToken(jwt);        // Attach raw access token JWT extracted from bearer/cookie        request.accessTokenJWT = jwt;
        this.logger.verbose(          `Authenticated User: ${JSON.stringify(request.user)}`,        );        return true;      }    } catch (ex) {      this.logger.warn(`Cannot validate access token: ${ex}`);    }`

For me it is never called, especially when it is running on Kubernetes and the issuer is or might be the problem.

**Comment by ferrerojosh** [comment]
I'll make a flag to disable token validation (which is inherently bad, but probably useful for development)

**Comment by EFritzsche90** [comment]
> I'll make a flag to disable token validation (which is inherently bad, but probably useful for development)

+1 for that

**Comment by gwx868323** [comment]
Dear all, is there the same fix for springboot adaptor?
