### ISSUE TITLE
Express support?

### ISSUE THREAD

**Issue by mghstehr** [ferrerojosh/nest-keycloak-connect#42]
You wrote "Compatible with Fastify platform.".
Does it mean, it will not work, when the default Express base is used ?
And if not working on Express base, are you planning to support it in the near future ?

Thanks
Matthias

**Comment by ferrerojosh** [comment]
It should work with base express by default. NestJS allows you to either use express or fastify and it depends on what you use.

The library adapted itself has full support for express.
