### ISSUE TITLE
Decorator for authenticated user

### ISSUE THREAD

**Issue by jalorenz** [ferrerojosh/nest-keycloak-connect#43]
Hi John,

first of all thanks a lot for this package :)

While using your package i asked myself, how can i receive user information like the user id. After digging the code i saw that you already assign the user information to the request object. Maybe you should write that in the documentation because other people might have the same question.

P.S.: the following decorator might be some syntax sugar:

```
import { createParamDecorator, ExecutionContext } from "@nestjs/common"

export const AuthenticatedUser = createParamDecorator((_data: unknown, ctx: ExecutionContext) => {
  const req = ctx.switchToHttp().getRequest()
  return req.user
})
```

Have a nice day! :)

**Comment by ferrerojosh** [comment]
Hello! Feel free to do a pull request for this. Would gladly accept this decorator into the library.

**Comment by ferrerojosh** [comment]
I added it myself since I wanted to release 1.5.0 today.

**Comment by erald14** [comment]
@ferrerojosh  good job
