### ISSUE TITLE
@AllowAnyRole is confusing

### ISSUE THREAD

**Issue by ferrerojosh** [ferrerojosh/nest-keycloak-connect#45]
As of the moment, `@AllowAnyRole` decorator is quite confusing. I am planning to deprecate this decorator in favor of a better name. It also confused developers since they are using it alone when `@Roles` is supposedly be used together with it (yes `@AllowAnyRole` won't do anything without `@Roles`).

I can take it any suggestions you like for this.

**Comment by jalorenz** [comment]
What do you think about an additional parameter for the decorator? I thought about some kind of matching mode, for example MatchingMode.ANY and MatchingMode.ALL. MatchingMode.ALL could be the default value.

```
@Roles({ roles: ["admin", "other"], matchingMode: MatchingMode.All })
```

**Comment by ferrerojosh** [comment]
> What do you think about an additional parameter for the decorator? I thought about some kind of matching mode, for example MatchingMode.ANY and MatchingMode.ALL. MatchingMode.ALL could be the default value.
> 
> ```
> @Roles({ roles: ["admin", "other"], matchingMode: MatchingMode.All })
> ```

I'll take this suggestion into account, thanks!

**Comment by aakay** [comment]
Hi @ferrerojosh , when will the changes in #54 become available? I need to use "any" matching, but `@AllowAnyRole` is deprecated.

Do you have a time estimation? Thanks in advance
