### ISSUE TITLE
Problem validating token using client_credentials grant

### ISSUE THREAD

**Issue by mvtavares** [ferrerojosh/nest-keycloak-connect#51]
Hello guys,

Thanks for the great module, is really helpful. 

I'm using keycloak v12.0.4 and nest-keycloak-connect v1.5.2.

I don't know if i'm doing something wrong, but i'm getting the following message when trying to use an protected route after getting an client_credentials token: 

-  [Keycloak] Cannot validate access token: Error: Error fetching account

If i get a password grant, than everything works. I believe the problem is at the auth.guard.ts, at line 81:

`request.user = await this.keycloak.grantManager.userInfo(jwt);
`

At this point, keycloak throws the following exception: 

```
11:42:42,883 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-53) Uncaught server error: java.lang.NullPointerException: Null keys are not supported!
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
```

Is it possible that, in client credentials grant, we should not get this userInfo ? Or maybe i'm missing something in the service account configuration ?

Thanks in advance for the help.

**Comment by ferrerojosh** [comment]
I'll look into this, thanks.

**Comment by dkfiresky** [comment]
I would like to report similar behavior.
It looks like nothing happening after logging these lines:

```
[Keycloak] User JWT: .....JWT goes here....
```

I have not found any errors in the Keycloak logs. And it seems like it works sometimes just fine, but then on another computer with same setup (using Keycloak exported realm.json) it stops without reason.

**Comment by ferrerojosh** [comment]
Also may I ask for the use-case for this ? I'm assuming Keycloak should already be the client/secret internally as a service account to authenticate/authorize using the jwt provided by the logged-in user (bearer/cookies). This service account is automatically enabled when you turn on authorization at the client level. Service accounts don't have user information hence the error encountered.

**Comment by mvtavares** [comment]
Hi Josh,

The use-case is when you're have some protected endpoints could to be used by clients/customers, but also by other microservices/batches which would not have a password grant, but a client_credentials without any user associated.

Does that make sense?

tks,

Marcus.

**Comment by ferrerojosh** [comment]
I got the idea. Thanks. I'm thinking of changing the user object to just parse the access token jwt, is that okay for you ?

**Comment by mvtavares** [comment]
Sure, that would be great.

Thanks a lot!
