### ISSUE TITLE
Is it possible to protect ServeStatic and files?

### ISSUE THREAD

**Issue by Brandejs** [ferrerojosh/nest-keycloak-connect#61]
Hi,

is there a way to protect static files? 

1. Serve static using https://docs.nestjs.com/recipes/serve-static

2. Controller files. Accessible from the browser

```
@Get('download/:fileId')
async download(@Res() response: Response, @Param('fileId') fileId: string, @AuthenticatedUser() user) { 
  const file = getFile(filed)
  if(hasAccessToThisFile(file, user)) {
   response.download(file, 'myFile.pdf')
  }
}
```

accessible via browser "localhost:3333/files/download/MyFileId" (No authorization header)

**Comment by ferrerojosh** [comment]
Hello! The library should support retrieving authentication jwt from from cookies. I dunno if that works for you.
