### ISSUE TITLE
Keycloak.json file config support

### ISSUE THREAD

**Issue by jbpin** [ferrerojosh/nest-keycloak-connect#63]
We just update our dependency to the latest version and we can't start our app using the keycloak.json configuration flow anymore. (v1.4 to v1.6)

```
Cannot read property 'useNestLogger' of null
```

There is a way to still use keycloak.json file with this version ?

**Comment by ferrerojosh** [comment]
This is a bug. Thanks. Will do a quick fix.

**Comment by jbpin** [comment]
I think I still have `Cannot read property 'tokenValidation' of null` ? is it possible ?
