### ISSUE TITLE
Is it possible to change the realm on runtime?

### ISSUE THREAD

**Issue by doshimehul** [ferrerojosh/nest-keycloak-connect#66]
We are building a multi tenant application where each sub domain would be one realm in keycloak, we are trying to see if there is a way we can set the realm dynamically from the subdomain?

**Comment by ferrerojosh** [comment]
This could be possible but it requires us to use multiple keycloak instances for this to happen which I don't want to do for now.

**Comment by doshimehul** [comment]
ok thanks for your reply.

what we are planning is having Single Keycloack instance which will have multiple realms, each realm will correspond to one tenant in our application.

If we are setting Factory service to make the realm dynamic, its not getting invoked on every API request.

Can you guide us to something which will help us to achieve the same?

thanks again!

**Comment by ferrerojosh** [comment]
Well its not really a dynamic solution, but you could use multiple modules (with its own controllers, guards, etc) which corresponds to different realms. The NestJS docs should clearly state how to do that. (https://docs.nestjs.com/modules)
