### ISSUE TITLE
How to use with Keycloak authorization resources, policies and permissions

### ISSUE THREAD

**Issue by simonjcarr** [ferrerojosh/nest-keycloak-connect#67]
How do I use @Scopes() with the @Resource() decorators to validate that user has the correct permissions and polices assinged. 

This might be an issue with my knowledge of Keycloak, or a misunderstanding of how the decorator terminology is used in this library.

I assumed that the combination of @Resource() at the controller level with @Scopes() at the method level, along with the logged-in user, would allow me to create Resources and Permission in Keycloak and have this library validate them for a given user.

Can someone give me some context by providing an example of adding a Scope and a Resource to the JWT in keycloak and how I would interact with them using @Resource() and @Scope()

**Comment by ferrerojosh** [comment]
You need to define your Resources and Scopes in your Keycloak server. This library allows you to validate or in technical terms, request a UMA ticket to your Keycloak server, to cross-check whether the user is allowed so by stating the endpoint's required scope and the defined resource.

For more information, you can simply drop by their official AuthZ docs: https://www.keycloak.org/docs/latest/authorization_services/

Also this library comes with an example project which you view here: https://github.com/ferrerojosh/nest-keycloak-connect/tree/master/example
