### ISSUE TITLE
Remove the requirement for a clientSecret

### ISSUE THREAD

**Issue by simonjcarr** [ferrerojosh/nest-keycloak-connect#68]
In our use case, we set up a keycloak client to represent an application.

The client roles we assign to users in that single client are then used by both the web GUI and the API. We don't have to worry if our GUI and API roles are in sync.

I.e if a user is given the role `create_purchase_order` in a single client
1. They will be able to access the create purchase order screen in the GUI
2. The API will give them access to the /purchaseorder POST endpoint

If you are forced to use a secret to make your Keycloak client work with nest JS, then a second client is required for the GUI  because keycloak-js does not allow a clientSecret in the browser for security reasons.

**Comment by ferrerojosh** [comment]
I might be wrong but this library is an adapter for the official Node.JS Keycloak Library (https://github.com/keycloak/keycloak-nodejs-connect). 

Assuming your Web GUI is built on some form of javascript, you should be using KeycloakJS (https://www.keycloak.org/docs/latest/securing_apps/#_javascript_adapter) on it.  

It allows you to use authorization code flow which you'll get your JWT token to send into the application server that is using this library.

**Comment by ferrerojosh** [comment]
Also as for your use of single client, it is not recommended to use the same client for both API and WebUI. It is a severe security issue and could cause a lot of problems. It is recommended to make a public client (which can authorize users and get the JWT you want) and a server application client (which can issue UMA tickets to the keycloak instance and validate them with the provided JWT issued by the public client).
