### ISSUE TITLE
Set keycloak-connect as a peerDependency

### ISSUE THREAD

**Issue by thiagodelgado111** [ferrerojosh/nest-keycloak-connect#69]
Hi there, @ferrerojosh! First of all, great job! This library is excellent! I wonder if we could set `keycloak-connect` as a peerDependency instead of a direct dependency. We are having some trouble with `keycloak-connect` and we'd like to use our own fork/version. Do you have any thoughts on it?

P.S: Let me know if you need help maintaining `nest-keycloak-connect` :)

**Comment by ferrerojosh** [comment]
This seems to be a good idea, would need to update the docs for it.

**Comment by thiagodelgado111** [comment]
PR updated: https://github.com/ferrerojosh/nest-keycloak-connect/pull/73

**Comment by EFritzsche90** [comment]
@thiagodelgado111 : Can you just give an example of how to use your own fork of keycloak-connect instead of the peer dependency?

**Comment by thiagodelgado111** [comment]
You can just install it from GitHub. `npm install thiagodelgado111/keycloak-nodejs-connect#branch`

**Comment by EFritzsche90** [comment]
But is this recognized due to another name? It is not named "keycloak-connect".
