### ISSUE TITLE
TokenValidation example in README does not adhere to comment

### ISSUE THREAD

**Issue by sirkrypt0** [ferrerojosh/nest-keycloak-connect#71]
Hey, I just read the README's getting started and thought that the `tokenValidation` in the following snippet (taken from the README) should be `TokenValidation.ONLINE`.

```js
      // optional, already defaults to online validation
      tokenValidation: TokenValidation.NONE,
```

Just like the `policyEnforcement` mode is set to `permissive` following the comment.

```js
      // optional, already defaults to permissive
      policyEnforcement: PolicyEnforcementMode.PERMISSIVE,
```

**Comment by ferrerojosh** [comment]
Ah this should be a quick change to the read me, thanks.
