### ISSUE TITLE
1.7.0 release missing built js files

### ISSUE THREAD

**Issue by richardallen** [ferrerojosh/nest-keycloak-connect#74]
First, thanks for the work on this project!

I installed release 1.7.0 for Nest 8 support, but the NPM package only has TypeScript files. Looks like the build wasn't packaged, just the source.

**Comment by rordenerena** [comment]
Yes, the same for me. 

I've tried to downgrade to 1.6.1 version and the result when I run the `npm run start:dev` is the same, an error like this: `error TS2307: Cannot find module 'nest-keycloak-connect' or its corresponding type declarations`

**Comment by EFritzsche90** [comment]
1.7.0-alpha01 is working for me. 

https://www.npmjs.com/package/nest-keycloak-connect/v/1.7.0-alpha01

**Comment by ferrerojosh** [comment]
Sorry this was a problem for the new release scripts, will be releasing the correct one immediately.
