### ISSUE TITLE
How can i get client information ("id" not clientId) from access_token

### ISSUE THREAD

**Issue by codextech** [ferrerojosh/nest-keycloak-connect#75]
Jwt only gives user information and clientId, how can I get ID of the client as shown in the image

**I CAN GET CLIENT DETAILS FROM THIS URL**
https://${SERVER_URL}/auth/admin/realms/master/clients?clientId=test
but i want to save my api call for getting Id

** I want to get client information "Id"  within jwt**

 Any help/information will be helpful for me.
 
 ![image](https://user-images.githubusercontent.com/21341120/127975211-27c9df29-f735-4b26-941a-dfe205176d67.png)

**Comment by ferrerojosh** [comment]
The library does not have control over this behavior as it is only using your client provided access token (which came from the user logging in into keycloak).

If you want something to start off, checkout Keycloak Mappers (https://www.keycloak.org/docs/latest/server_admin/index.html#_protocol-mappers).
