### ISSUE TITLE
How to use keycloak-connect as peer dependency?

### ISSUE THREAD

**Issue by EFritzsche90** [ferrerojosh/nest-keycloak-connect#76]
Hi @ferrerojosh.

I really love your project and with the latest release there were some really helpful features. Regarding the introduction of keycloak-connect as peer dependency I might have a stupid question.

I forked this library, because I did some adjustments (https://www.npmjs.com/package/@ef-company/keycloak-connect). Now, I would like to use it instead of the original one and without forking your project. Could you give an example of how this could work? It would help me a lot.

Thanks in advance!

**Comment by ferrerojosh** [comment]
You just need to add keycloak-connect on your project. That is why the docs now state to install both the library and keycloak-connect.
```bash
npm install keycloak-connect nest-keycloak-connect
```

**Comment by ferrerojosh** [comment]
Oh I think I interpreted the question wrong.
You should be able to use your own forked version by providing the link.

```bash
npm install <your-github-url>
```
I don't know if it works, but you can alias an npm package:
```bash
npm install keycloak-connect@npm:@ef-company/keycloak-connect
```

Checkout https://docs.npmjs.com/cli/v7/commands/npm-install for more info.
