### ISSUE TITLE
Nest not start

### ISSUE THREAD

**Issue by yosdanybm** [ferrerojosh/nest-keycloak-connect#8]
Nest app does not start me, and I have it configured exactly as in the documentation, this is the error:
![nest](https://user-images.githubusercontent.com/12848126/82745617-83118a80-9d54-11ea-9ac2-fa451615dc95.PNG)

**Comment by yosdanybm** [comment]
I solved with the fork by @cenkce, in the master you have a regression.

Link to fork: https://github.com/cenkce/nest-keycloak-connect

**Comment by ferrerojosh** [comment]
Fixed in 1.0.10. Thanks.
