### ISSUE TITLE
Get Correct errors when validation fails. 

### ISSUE THREAD

**Issue by erald14** [ferrerojosh/nest-keycloak-connect#80]
Right now I have noticed that when a token is invalid it returns 500 internal error.
Any way to change this?

**Comment by ferrerojosh** [comment]
It should be throwing an UnauthorizedException. I only encounter this when I'm using the library locally (during my own testing). For some reason Nest won't catch the exception properly, I'll investigate this further as to why.

**Comment by erald14** [comment]
@ferrerojosh  I really appreciate it, this is important to us.

**Comment by ferrerojosh** [comment]
I found the issue, it occurred when I added changes for token validation methods. Will do a patch soon.

**Comment by erald14** [comment]
thanks

**Comment by erald14** [comment]
@ferrerojosh  any update on this?

**Comment by erald14** [comment]
Thanks @ferrerojosh

**Comment by erald14** [comment]
Please create a donate link or anything, I'd like to contribute
