### ISSUE TITLE
Using Roles() results 403 Forbidden resource

### ISSUE THREAD

**Issue by papastepano** [ferrerojosh/nest-keycloak-connect#81]
Using token validation method: ONLINE - 
@Roles({ roles: ['basic'] }) returns 403 Forbidden for currently authenticated user with _basic_, although the role is assigned to realm and client.

```
{
    "exp": 1628960884,
    "iat": 1628960584,
    "auth_time": 1628960583,
    "jti": "365e237e-fcd0-441a-xxx-xxxxxxxxx",
    "iss": "http://localhost:8080/auth/realms/xxxxx",
    "sub": "33f9166d-4f4a-454f-9528-xxxxxxxxxxxx",
    "typ": "Bearer",
    "azp": "xyz-client",
    "session_state": "76f16231-xx-485c-b67f-xxxxx",
    "acr": "1",
    "allowed-origins": [
        "http://localhost:3000"
    ],
    "realm_access": {
        "roles": [
            "basic"
        ]
    },
    "resource_access": {
        "xyz-client": {
            "roles": [
                "basic",
                "pro"
            ]
        }
    },
    "scope": "profile email",
    "sid": "76f16231-xxx-xxxx-b67f-xxxxxxx",
    "email_verified": true,
    "name": "John Doe",
    "preferred_username": "john",
    "given_name": "John",
    "family_name": "Doe",
    "email": "john.doe@example.com"
}
```

**Comment by ferrerojosh** [comment]
For realm level roles, you need to prefix it with `realm:` so the resulting annotation would become `@Roles({ roles: ['realm:basic'] })`

**Comment by papastepano** [comment]
Actually this does not resolve the issue in question. 
The issue is:
@Role decorator does not work for neither Realm or Client

**Comment by ferrerojosh** [comment]
I'll take a look into this.

**Comment by ferrerojosh** [comment]
I need more information, in my testing I get forbidden when I set PolicyEnforment into ENFORCING and my route doesn't have a Scope defined. If possible I need the configs and route code used.

This is a major problem and I think I need to merge both guards together in the next major version. Unless Nest has a way to pipeline guards.

**Comment by papastepano** [comment]
Hi @ferrerojosh, thank you for taking the time to look into this, as it is an important feature for me.
In my setup I have:
```typescript
policyEnforcement: PolicyEnforcementMode.PERMISSIVE,
```
And my nestjs route looks like this:
```typescript
  @Get()
  @Roles({ roles: ['pro'], mode: RoleMatchingMode.ALL })
  getHello(): string {
    return this.appService.getHello();
  }
```
I actually dont have scope Injectable. Do you get roles to work in your tests? And if yes under what configs?
Thanks!

**Comment by ferrerojosh** [comment]
Yes I do have it working in my tests.

I have the configuration:
```typescript
  policyEnforcement: PolicyEnforcementMode.PERMISSIVE,
  tokenValidation: TokenValidation.ONLINE
 ```
  
  With the following [controller](https://github.com/ferrerojosh/nest-keycloak-connect/blob/master/example/src/product/product/product.controller.ts):
```typescript
@Controller('product')
@Resource(Product.name)
export class ProductController {
  constructor(private service: ProductService) {}

  @Get()
  @Public(false)
  @Scopes('View')
  async findAll() {
    return await this.service.findAll();
  }

  @Get(':code')
  @Roles({ roles: ['realm:basic'] })
  async findByCode(@Param('code') code: string) {
    return await this.service.findByCode(code);
  }

  @Post()
  @Scopes('Create')
  async create(@Body() product: Product) {
    return await this.service.create(product);
  }

  @Delete(':code')
  @Scopes('Delete')
  async deleteByCode(@Param('code') code: string) {
    return await this.service.deleteByCode(code);
  }

  @Put(':code')
  @Scopes('Edit')
  async update(@Param('code') code: string, @Body() product: Product) {
    return await this.service.update(code, product);
  }
}
```

Injectable should not be required. it is important that it is a controller.

**Comment by papastepano** [comment]
Interesting. @ferrerojosh Could the problem be in the @Resource()? What should it exactly contain?
Another thing, that I am suspecting is keycloak's client configuration. Do you have some specific setting there?

**Comment by ferrerojosh** [comment]
> Interesting. @ferrerojosh Could the problem be in the @resource()? What should it exactly contain?
> Another thing, that I am suspecting is keycloak's client configuration. Do you have some specific setting there?
> 
> ```ts
> import { Controller, Get, Scope } from '@nestjs/common';
> import {
>   Public,
>   Resource,
>   RoleMatchingMode,
>   Roles,
>   Scopes,
>   Unprotected,
> } from 'nest-keycloak-connect';
> import { AppService } from './app.service';
> 
> export class Resouce {
>   name: string;
> }
> 
> @Controller()
> @Resource(Resouce.name)
> export class AppController {
>   constructor(private readonly appService: AppService) {}
> 
>   @Get()
>   @Scopes('View')
>   @Roles({ roles: ['basic'], mode: RoleMatchingMode.ALL })
>   getHello(): string {
>     return this.appService.getHello();
>   }
> }
> ```

Your resource name should be what you configured in Keycloak's AuthZ (admin portal) configuration. `@Roles` should work without `@Resource` (which is combined with `@Scopes`) if you aren't using AuthZ. You can remove `ResourceGuard` in your module if you're mainly using `RoleGuard`.

**Comment by papastepano** [comment]
@ferrerojosh May I ask what version of Node are you using?

**Comment by ferrerojosh** [comment]
> @ferrerojosh May I ask what version of Node are you using?
> 
> Can you please specify how to configure this Resource in Keycloak's admin portal configuration?
> 
> With your setup
> 
> ```ts
> @Controller()
> @Resource(Resouce.name)
> export class AppController {
>   constructor(private readonly appService: AppService) {}
> 
>   @Get()
>   @Public(false)
>   @Scopes('View')
>   @Roles({ roles: ['basic'] })
>   getHello(): string {
>     return this.appService.getHello();
>   }
> }
> ```
> 
> I currently get the following:
> 
> ```
> [Nest] 38504   - 16.08.2021, 11:44:05   [Keycloak] Protecting resource [ Resouce ] with scopes: [ View ]
> [Nest] 38504   - 16.08.2021, 11:44:05   [Keycloak] Resource [ Resouce ] denied to [ user1 ]
> ```

```bash
> node -v
v14.16.1
```

The realm setup is too long, its inside the example folder of this repository. You should find out more in Keycloak's AuthZ documentation: https://www.keycloak.org/docs/latest/authorization_services/index.html

**Comment by imvenx** [comment]
it fixed the problem for me to use "realm:role" after trying with my realm name for a while I realized you literally meant "realm" and not "insert-your-realm-name" :D Thanks! @ferrerojosh
