### ISSUE TITLE
support ssl-required in keycloak configuration

### ISSUE THREAD

**Issue by itzikntn** [ferrerojosh/nest-keycloak-connect#87]

**Comment by ferrerojosh** [comment]
I see they updated their types with ssl-required, although it wasn't used explicitly in the config files.

**Comment by itzikntn** [comment]
Great ! , Thank you very much
Have a good weekend !


בתאריך יום ו׳, 24 בספט׳ 2021, 1:59, מאת John Joshua Ferrer ‏<
***@***.***>:
