### ISSUE TITLE
Non-interactive server-side login to Keycloak

### ISSUE THREAD

**Issue by TrumanRu** [ferrerojosh/nest-keycloak-connect#88]
keycloak-connect `GrantManager` interface has `obtainDirectly(username: string, password: string): Promise<Grant>` method.

How can I call it from nest-keycloak-connect?

I need to reroute POST request from NestJS controller to Keycloak realm then send obtained JWT to frontend. Looks like an authentication proxy.

PS: I understand the main goal of this module is only verify JWT obtained by frontend.

**Comment by ferrerojosh** [comment]
Inject the keycloak instance. It is exported.

```typescript
import KeycloakConnect from 'keycloak-connect';
import { KEYCLOAK_INSTANCE } from 'nest-keycloak-connect';

constructor(
  @Inject(KEYCLOAK_INSTANCE)
  keycloak: KeycloakConnect.Keycloak
) {
  this.keycloak.grantManager.obtainDirectly("user", "pass");
}
```
