### ISSUE TITLE
Yarn PnP compatibility

### ISSUE THREAD

**Issue by atoi** [ferrerojosh/nest-keycloak-connect#89]
I have a monorepo set up using yarn workspaces. Nest app refuses to start producing the following error:

`Error: nest-keycloak-connect tried to access @nestjs/core, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.`

I suppose it is this case exactly:
https://classic.yarnpkg.com/en/docs/pnp/troubleshooting/#toc-is-trying-to-require-without-it-being-listed-in-its-dependencies

As far as I can see `@nestjs/core` is actually mentioned in the dependencies, but `dev` ones.  

I can make yarn "shut up" by using `pnpMode: loose` but that doesn't feel right.
Would be great if `nest-keycloak-connect` worked with yarn pnp "out of the box".

**Comment by ferrerojosh** [comment]
Ah I think this is because I only listed `@nestjs/common` on `peerDependencies` since it will transitively bring up `@nestjs/core` as well. This will be a quick fix, I just need to add `@nestjs/core` on peer as well.
