### ISSUE TITLE
Support for @nestjs/graphl 9

### ISSUE THREAD

**Issue by lovetodream** [ferrerojosh/nest-keycloak-connect#91]
nest-keycloak-connect requires an optional peer dependency of @nestjs/graphql 6, 7 or 8. Is it possible to add version 9 or does it require any major changes?

**Comment by ferrerojosh** [comment]
It should technically still work, I don't see any major breaking changes that will affect the library itself. Will add version 9 on the next release.

Also according to nestjs docs, it should work correctly:

> `@nestjs/graphql@^9` is compatible with Apollo v3 (check out Apollo Server 3 migration guide for more details), while `@nestjs/graphql@^8` only supports Apollo v2 (e.g., apollo-server-express@2.x.x package). Both versions (v9 and v8) are fully compatible with Nest v8 (`@nestjs/common@^8`, `@nestjs/core@^8`, etc.).
