### ISSUE TITLE
Support for multi tenancy

### ISSUE THREAD

**Issue by dennismeister93** [ferrerojosh/nest-keycloak-connect#93]
Hey :)
is it planned or already possible to support multi tenancy with this nest module?
In other projects (without nestjs) I'm using https://www.npmjs.com/package/keycloak-connect-multirealm to support more than only one issuer to check for.

Looking forward to hear from you! :)

**Comment by ferrerojosh** [comment]
> Hey :) is it planned or already possible to support multi tenancy with this nest module? In other projects (without nestjs) I'm using https://www.npmjs.com/package/keycloak-connect-multirealm to support more than only one issuer to check for.
> 
> Looking forward to hear from you! :)

Sure. I think this can be made possible.

**Comment by ferrerojosh** [comment]
Hello! I made a pre-release for this. `1.8.0-alpha.1` is the version or you can just `npm install nest-keycloak-connect@next`.

To use multi tenant, just simply pass a `null` realm or leave it `undefined`.

Other options would be defining the `realmResolver` function that is added to the configuration options.

Example:
```typescript
import { Injectable } from '@nestjs/common';
import { KeycloakConnectOptions, KeycloakConnectOptionsFactory, PolicyEnforcementMode, TokenValidation } from 'nest-keycloak-connect';

@Injectable()
export class KeycloakConfigService implements KeycloakConnectOptionsFactory {

  createKeycloakConnectOptions(): KeycloakConnectOptions {
    return {
      authServerUrl: 'http://localhost:8180/auth',
      realmResolver: (request) => {
        return request.get('host').split('.')[0];
      },
      clientId: 'nest-api',
      secret: 'secret-key-goes-here',
    };
  }
  
}
```

Notable Changes:
- The `request` object should be the request for your platform `express` or `fastify`.
- `realm` option now made optional (will attempt to resolve realm based on issuer jwt)

Please let me know if you find any issue as I have short time to prepare for a multi tenant lab to test on.

**Comment by pedroCore** [comment]
Hi! First of all, this feature will bulk this library a lot. There is not that many libraries that have the muti-realm support for Keycloak. 

I know that this is an alpha version, but it seems there is a problem using registerAsync with the version 1.8.0-alpha.1, it fails with unresolved dependencies, in this case the KeycloakMultiTenantService:

```diff
-  [Nest] 5800  13/12/2021, 15:13:38   ERROR [ExceptionHandler] Nest can't resolve dependencies of the AuthGuard (KEYCLOAK_INSTANCE, KEYCLOAK_CONNECT_OPTIONS, KEYCLOAK_LOGGER, ?, Reflector). Please make sure that the argument KeycloakMultiTenantService at index [3] is available in the AuthModule context.
- Potential solutions:
- If KeycloakMultiTenantService is a provider, is it part of the current AuthModule?
- If KeycloakMultiTenantService is exported from a separate @Module, is that module imported within AuthModule?
- @Module({
-    imports: [ /* the Module containing KeycloakMultiTenantService */ ]
- }) -

Error: Nest can't resolve dependencies of the AuthGuard (KEYCLOAK_INSTANCE, KEYCLOAK_CONNECT_OPTIONS, KEYCLOAK_LOGGER, ?, Reflector). Please make sure that the argument KeycloakMultiTenantService at index [3] is available in the AuthModule context.

Potential solutions:
 - If KeycloakMultiTenantService is a provider, is it part of the current AuthModule?
 - If KeycloakMultiTenantService is exported from a separate @Module, is that module imported within AuthModule?
  @Module({
   imports: [ /* the Module containing KeycloakMultiTenantService */ ]
  })
```

I'am using a different module instead of the app module directly to encapsulate the integration, but tested like in the example provided in the repo (directly import in the app module) and the error is the same.

Anyway, looking forward to seeing this feature in the next release! Thank you! :)

**Comment by emaung** [comment]
Heya @ferrerojosh thanks for your hard work on this library. This functionality is quite essential for us as we use multiple realms to segregate customers. Just wondering what is the status of the alpha version? Do you know when would that be promoted to release? Is there any work pending or need help with?

**Comment by emaung** [comment]
heya, @pedroCore I think I found an issue, It is missing `KeycloakMultiTenantService` in the async provider registration.

**Comment by ferrerojosh** [comment]
Hello guys, sorry for the delay, I added a new alpha release with the fixes @emaung came up with. Thank you @pedroCore for telling that async registration was not working. Also found out myself that realm parsing using issuer from jwt token was not working at all.

If everything works well I'll release it soon as 1.8.0.

**Comment by emaung** [comment]
Heya @ferrerojosh thank you for looking into this. We had actually use the realm resolver and read the issuer from the token manually. So not aware of the realm parsing issue. Additionally we only wanted to allow some realms to have access, so we have added some realm whitelisting in the realmResolver logic.

**Comment by ferrerojosh** [comment]
Released a new alpha release with a resolver for realm secrets (#102)
