### ISSUE TITLE
Logging changes in Nest 8

### ISSUE THREAD

**Issue by gogo199432** [ferrerojosh/nest-keycloak-connect#94]
My logs are getting swallowed again on Nest 8. It seems like they changed the logging slightly, please take a look at their guide under Logger breaking changes:

https://docs.nestjs.com/migration-guide

**Comment by gogo199432** [comment]
My bad, one of my routes was grabbing the execution so my log statements were never hit...still might be worth to take a look?

**Comment by ferrerojosh** [comment]
If you're passing useNestLogger = true, it shouldn't be a problem.
